import json,re,hashlib
from pathlib import Path
from html import unescape
R=Path.cwd();en=json.loads((R/'public/content/mark-1-1-13/resources.json').read_text());sp=json.loads((R/'public/content/spa/mark-1-1-13/pack.json').read_text()); sha=lambda b:hashlib.sha256(b).hexdigest();plain=lambda s:re.sub(r'\s+',' ',unescape(re.sub('<[^>]+>',' ',s))).strip(); terms={re.search(r'-t(\d+)-',x['id'])[1]:x for x in sp['terms']};media={x['id']:x for x in sp['media']};out=[];inputs=[]
for r in en:
 key=re.search(r'-t(\d+)-',r['content_id']);match=terms.get(key[1]) if key else media.get(r['content_id']);body=r.get('content','');body=json.dumps(body,ensure_ascii=False) if not isinstance(body,str) else body;existing=[x for x in sp['supplements'] if x['source'].get('sourceId')==r['content_id'] or x['targetId']==(match or {}).get('id')];row={'englishId':r['content_id'],'kind':r['kind'],'englishTitle':r['title'],'spanishId':match['id'] if match else None,'identityStatus':'present-semantic-parity-pending' if match else 'absent-from-current-Spanish-pack','sourceCharacters':len(plain(body)),'englishBodySha256':sha(body.encode()),'existingSupplementIds':[x['id'] for x in existing],'requiresVideoTranscript':r['kind']=='video'};out.append(row);inputs.append({**row,'englishHtml':body,'englishSource':r['source'],'rights':r['rights'],'existingSpanishOriginalHtml':match.get('originalHtml') if match else None,'existingSpanishSource':match.get('source') if match else None,'existingSupplements':existing})
old=json.loads(Path('/tmp/fia-spanish-audio-preparation/REQUEST-LEDGER.json').read_text());summary={'main':'e4a040fef5c5ba4dc8cfb711f4943dcd632ca1d9','englishResources':len(en),'SpanishTerms':len(sp['terms']),'SpanishMedia':len(sp['media']),'existingSupplements':len(sp['supplements']),'matchedEnglishIdentities':sum(x['spanishId'] is not None for x in out),'missingEnglishIdentities':[x['englishId'] for x in out if not x['spanishId']],'unionResourceIdentities':len(sp['terms'])+len(sp['media'])+sum(x['spanishId'] is None for x in out),'englishResourceSourceCharacters':sum(x['sourceCharacters'] for x in out),'missingResourceEnglishCharacters':sum(x['sourceCharacters'] for x in out if not x['spanishId']),'priorRequests':old['requestCount'],'priorCharacters':old['characters'],'currentPackSha256':sha((R/'public/content/spa/mark-1-1-13/pack.json').read_bytes()),'priorPackUnchanged':sha((R/'public/content/spa/mark-1-1-13/pack.json').read_bytes())==old['sourcePackSha256'],'expandedAudioCharacters':None,'expandedAudioCharactersPending':'Spanish translations and reviewed spoken projections/notices do not exist yet; do not substitute English source counts','providerCalls':0}
for name,data in [('RESOURCE-MAP.json',out),('TRANSLATION-INPUTS.json',inputs),('SUMMARY.json',summary)]: (R/'audit'/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
# Safe private historical binding attestation without printing identifiers.
a=json.loads((R/'evidence/release/private-originals/mark-1-1-13-manifest.json').read_text());b=json.loads((R/'evidence/release/private-originals/terms-manifest.json').read_text());binding={'sameHistoricalDefaultVoice':a.get('voiceId')==b.get('voiceId') and bool(a.get('voiceId')),'privatePointers':['evidence/release/private-originals/mark-1-1-13-manifest.json','evidence/release/private-originals/terms-manifest.json'],'filesSha256':[sha((R/p).read_bytes()) for p in ['evidence/release/private-originals/mark-1-1-13-manifest.json','evidence/release/private-originals/terms-manifest.json']],'currentProviderAccessVerified':False,'accountBalanceVerified':False,'modelProjectionVerified':False};(R/'audit/VOICE-BINDING.json').write_text(json.dumps(binding,indent=2)+'\n');print(json.dumps(summary,indent=2))
