import visualManifest from '../../public/audio/visual-resources/manifest.json' with {type:'json'};
import nextActions from '../../public/audio/next-actions/manifest.json' with {type:'json'};
import transitions from '../../public/audio/activity-transitions/manifest.json' with {type:'json'};
import termManifest from '../../public/audio/terms/manifest.json' with {type:'json'};
import recordingManifest from '../../public/audio/mark-1-1-13/manifest.json' with {type:'json'};
export const approvedAudioManifest={entries:[...nextActions.entries,...transitions.entries,...recordingManifest.entries,...termManifest.entries,...visualManifest.entries]};
const sha=async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
/** Verify only the selected source recording before playback; no runtime provider calls. */
export class AudioController {
 constructor(AudioType,onState,{manifest=approvedAudioManifest,fetcher=(...args)=>fetch(...args),urlApi=URL}={}){this.AudioType=AudioType;this.onState=onState;this.manifest=manifest;this.fetcher=fetcher;this.urlApi=urlApi;this.generation=0;this.events=[];}
 emit(status,error=''){this.status=status;this.onState({status,error,sourceId:this.item?.id,title:this.item?.title??'',fullTitle:this.item?.fullTitle??this.item?.title??'',owner:this.item?.owner,elapsed:Number.isFinite(this.audio?.currentTime)?this.audio.currentTime:0,duration:Number.isFinite(this.audio?.duration)?this.audio.duration:0,queued:!!this.queued,events:this.events.slice(-30)});}
 release(){if(this.objectUrl){this.urlApi.revokeObjectURL(this.objectUrl);this.objectUrl=null;}}
 clearGap(){clearTimeout(this.gapTimer);this.gapTimer=null;this.queued=null;}
 stop(){this.restoring=false;this.pendingRestore=null;this.clearGap();this.generation++;this.abort?.abort();if(this.audio){this.audio.pause();this.audio.removeAttribute?.('src');this.audio.load?.();this.audio=null;}this.release();this.item=null;this.emit('idle');}
 rate(){if(this.audio){this.audio.playbackRate=.95;this.audio.preservesPitch=true;}}
 restart(){if(this.restoring){this.speak(this.items.slice(this.itemIndex),null,this.onItemEnd);return;}this.clearGap();const token=this.generation;if(this.audio){this.audio.currentTime=0;this.rate();this.audio.play().catch(e=>{if(token===this.generation)this.emit('error',e.message);});}}
 pause(){if(this.queued){clearTimeout(this.gapTimer);this.gapTimer=null;this.emit('paused');return;}this.audio?.pause();}
 resume(){if(this.restoring)return;if(this.queued){const run=this.queued;this.clearGap();run();return;}const token=this.generation;this.rate();this.audio?.play().catch(e=>{if(token===this.generation)this.emit('error',`Playback could not resume: ${e.message}`);});}
 restore(items,checkpoint,onItemEnd=()=>{}){this.speak(items,null,onItemEnd,checkpoint);}
 checkpoint(){const e=this.manifest.entries.find(x=>x.id===this.item?.id);if(!e)return null;if(this.status==='error')return null;return{ownerDomain:this.item.owner==='guide'?'guide':this.item.owner==='scripture'?'scripture':'resources',clipId:e.id,sourceSha256:e.sourceSha256,outputSha256:e.sha256,offsetSeconds:Number.isFinite(this.audio?.currentTime)?this.audio.currentTime:this.pendingRestore?.offsetSeconds??0,phase:this.queued||this.pendingRestore?.phase==='gap'?'gap':this.audio?.ended?(this.item.stop?'discussion-ended':'terminal-ended'):'unfinished',...(this.queued||this.pendingRestore?.phase==='gap'?{nextClipId:this.items[this.itemIndex+1]?.id}: {})};}
 speak(items,_voice,onItemEnd=()=>{},restore=null){this.stop();this.items=items;this.onItemEnd=onItemEnd;this.pendingRestore=restore;this.restoring=!!restore;const token=this.generation;let index=0;this.abort=new AbortController();const next=async()=>{if(token!==this.generation)return;this.release();if(index>=items.length){this.emit('idle');return;}const item=items[index++];this.itemIndex=index-1;this.item=item;this.audio=null;const restoring=restore&&index===1;this.emit(restoring?'restoring':'starting');try{
 const entry=this.manifest.entries.find(e=>e.id===item.id);if(!entry||await sha(new TextEncoder().encode(item.text))!==entry.sourceSha256)throw Error('Recording does not match the selected source.');
 if(restoring&&(restore.clipId!==entry.id||restore.sourceSha256!==entry.sourceSha256||restore.outputSha256!==entry.sha256||!Number.isFinite(restore.offsetSeconds)||restore.offsetSeconds<0||restore.phase==='gap'&&items[index]?.id!==restore.nextClipId))throw Error('Saved recording no longer matches this source.');if(token!==this.generation)return;
 const response=await this.fetcher(entry.path,{signal:this.abort.signal});if(!response.ok||response.headers.get('content-type')?.split(';')[0]!=='audio/mpeg')throw Error('Recording unavailable or wrong file type.');const bytes=await response.arrayBuffer();if(bytes.byteLength!==entry.bytes||await sha(bytes)!==entry.sha256)throw Error('Recording integrity check failed.');if(token!==this.generation)return;
 this.objectUrl=this.urlApi.createObjectURL(new Blob([bytes],{type:'audio/mpeg'}));const audio=new this.AudioType(this.objectUrl);this.audio=audio;this.rate();
 const event=(type,status)=>{if(token!==this.generation)return;this.events.push({type,id:item.id,time:audio.currentTime});this.emit(status);};audio.onloadedmetadata=audio.ontimeupdate=()=>{if(token===this.generation&&this.audio===audio)this.emit(this.status);};audio.onplaying=()=>event('playing','playing');audio.onpause=()=>event('pause','paused');audio.onended=()=>{if(token!==this.generation)return;if(this.queued)return;event('ended','idle');if(index<items.length){this.queued=()=>{if(token!==this.generation)return;onItemEnd(item);void next();};this.emit('gap');this.gapTimer=setTimeout(()=>{const run=this.queued;if(!run||token!==this.generation)return;this.clearGap();run();},750);}else{onItemEnd(item);this.emit('idle');}};audio.onerror=()=>{if(token!==this.generation)return;this.generation++;this.release();this.emit('error','This verified recording could not decode or play.');};if(restoring){await new Promise((resolve,reject)=>{if(audio.readyState>=1)return resolve();audio.addEventListener('loadedmetadata',resolve,{once:true});audio.addEventListener('error',()=>reject(Error('Saved recording metadata unavailable')),{once:true});this.abort.signal.addEventListener('abort',()=>reject(Error('Restoration cancelled')),{once:true});audio.load?.();});if(token!==this.generation||this.audio!==audio)return;if(!Number.isFinite(audio.duration)||audio.duration<=0)throw Error('Saved recording duration unavailable');audio.currentTime=Math.min(restore.offsetSeconds,audio.duration);if(audio.seeking)await new Promise((resolve,reject)=>{audio.addEventListener('seeked',resolve,{once:true});this.abort.signal.addEventListener('abort',()=>reject(Error('Restoration cancelled')),{once:true});});if(token!==this.generation||this.audio!==audio)return;if(restore.phase==='gap'){this.queued=()=>{if(token!==this.generation)return;onItemEnd(item);void next();};}this.pendingRestore=null;this.restoring=false;this.rate();this.emit('paused');}else await audio.play();
 }catch(e){if(token===this.generation){this.generation++;this.release();this.emit('error',`Playback could not start: ${e.message}`);}}};void next();}
}
