import approved from '../../content-packs/spa/mark-1-1-13/manifest.json';
const base='/content/spa/mark-1-1-13/';
export const spanishIdentity=approved.textIdentity??`${approved.packId}/${approved.files[0].sha256}`;
export const languagePreferenceKey='fia-content-language-v1';
export async function verifiedBytes(response,entry){if(!response.ok)throw Error('Language file unavailable');const bytes=await response.arrayBuffer();const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==entry.sha256||bytes.byteLength!==entry.bytes)throw Error('Language file integrity check failed');return bytes;}
export async function loadSpanish(signal){const entry=approved.files.find(f=>f.path==='pack.json');for(const asset of approved.files.filter(f=>f.path!=='pack.json'&&!f.path.endsWith('.mp3')))await verifiedBytes(await fetch(base+asset.path,{signal}),asset);const bytes=await verifiedBytes(await fetch(base+'pack.json',{signal}),entry);if(signal?.aborted)throw new DOMException('Canceled','AbortError');const pack=JSON.parse(new TextDecoder().decode(bytes));if(pack.contentLanguage!=='spa'||pack.id!==approved.packId)throw Error('Unknown language pack');if(approved.preparedAudio){const descriptor=approved.preparedAudio;const audioBytes=await verifiedBytes(await fetch(descriptor.path,{signal}),descriptor);pack.preparedAudio=JSON.parse(new TextDecoder().decode(audioBytes));}return pack;}
export const spanishAsset=path=>base+path;
export function restoreSpanish(storage,pack){const fallback={groupId:pack.guide.ordinaryGroupIds[0],version:pack.scripture[0].id,view:'guide',query:'',resourceId:null};try{let raw=storage?.getItem(`fia-workspace/spa/${spanishIdentity}`);if(!raw&&pack.id==='spa-mrk-1-1-13-expanded-v2')raw=storage?.getItem('fia-workspace/spa/spa-mrk-1-1-13-source-v1/031635f2c922871e71bb679758642cb6e2e37a4779d7c1cc32e1b395d5706192');if(!raw)return {...fallback};const state=JSON.parse(raw);if(['ai-spa-from-BereanStandardBible-mark-1-1-13','ai-spa-from-unfoldingWordLiteral-mark-1-1-13','ai-spa-from-unfoldingWordSimplified-mark-1-1-13'].includes(state.version))state.version=fallback.version;if(!pack.guide.ordinaryGroupIds.includes(state.groupId)||!pack.scripture.some(v=>v.id===state.version)||!['languages','guide','scripture','resources'].includes(state.view)||typeof state.query!=='string'||state.resourceId!==null&&![...pack.terms,...pack.media].some(r=>r.id===state.resourceId))return {...fallback,notice:'Saved Spanish position was invalid; restored the first source group.'};return {groupId:state.groupId,version:state.version,view:state.view,query:state.query.slice(0,200),resourceId:state.resourceId};}catch{return {...fallback,notice:'Spanish position could not be restored; this session can continue.'};}}
export function saveSpanish(storage,state){try{if(!storage)return false;const{notice,...persist}=state;storage.setItem(`fia-workspace/spa/${spanishIdentity}`,JSON.stringify(persist));return true;}catch{return false;}}
