export class OfflineController{
 constructor(onState,language='eng'){this.language=language;this.onState=onState;this.state={status:'checking',saved:false};}
 emit(value){this.state={...this.state,...value};this.onState(this.state);}
 async init(){try{if(!('serviceWorker'in navigator))throw Error('Offline saving is unavailable in this browser.');const reg=await navigator.serviceWorker.register('/sw.js');try{await reg.update();}catch(e){if(!reg.active)throw e;}const installing=reg.installing||reg.waiting;if(installing&&installing.state!=='activated')await new Promise((resolve,reject)=>{const changed=()=>{if(installing.state==='activated'){installing.removeEventListener('statechange',changed);resolve();}else if(installing.state==='redundant'){installing.removeEventListener('statechange',changed);reject(Error('Offline worker update failed.'));}};installing.addEventListener('statechange',changed);changed();});this.worker=reg.active||(await navigator.serviceWorker.ready).active;navigator.serviceWorker.addEventListener('message',this.listener=e=>{if(e.data?.type==='CACHE_ERROR')this.emit({status:'error',saved:false,corrupt:true,error:e.data.error});});await this.check();}catch(e){this.emit({status:'error',error:e.message});}}
 dispose(){if(this.listener)navigator.serviceWorker?.removeEventListener('message',this.listener);}
 request(type,id){return new Promise((resolve,reject)=>{if(!this.worker)return reject(Error('Offline saving is not ready.'));const channel=new MessageChannel();channel.port1.onmessage=e=>{if(e.data.progress){this.emit({status:'saving',...e.data});return;}if(e.data.done){channel.port1.close();resolve(e.data);}};this.worker.postMessage({type,id,language:this.language},[channel.port2]);});}
 async check(){const value=await this.request('STATUS');this.emit({...value,status:value.error?'error':'ready',error:value.error??''});return value;}
 async save(){this.id=crypto.randomUUID();this.emit({status:'saving',error:'',bytes:0,total:0});try{const value=await this.request('SAVE',this.id);this.emit({...value,status:value.error?'error':'ready'});}catch(e){this.emit({status:'error',error:e.message});}}
 cancel(){this.worker?.postMessage({type:'CANCEL',id:this.id});}
 async remove(){const value=await this.request('DELETE');this.emit({...value,status:value.error?'error':'ready',error:value.error??''});}
}
