import test from 'node:test';import assert from 'node:assert/strict';import {AudioController} from '../src/lib/audio.js';
class FakeAudio{static made=[];constructor(src){this.src=src;this.currentTime=0;FakeAudio.made.push(this);}play(){return Promise.resolve();}pause(){this.onpause?.();}removeAttribute(){}load(){}}
const fixture=()=>{const bytes=Buffer.from('fixture'),text='source',hash=x=>crypto.createHash('sha256').update(x).digest('hex');return {manifest:{entries:['S01-U001','S01-U002'].map(id=>({id,path:`/${id}`,bytes:bytes.length,sha256:hash(bytes),sourceSha256:hash(text)}))},fetcher:async()=>new Response(bytes,{headers:{'Content-Type':'audio/mpeg'}}),urlApi:{createObjectURL:()=> 'blob:fixture',revokeObjectURL(){}}};};
const until=async predicate=>{const deadline=Date.now()+10000;while(!predicate()&&Date.now()<deadline)await new Promise(r=>setTimeout(r,5));assert(predicate());};const ready=c=>until(()=>!!c.audio);
test('simulated HTMLAudio events advance only ended source units and suppress canceled callbacks',async()=>{const states=[],done=[];const c=new AudioController(FakeAudio,s=>states.push(s),fixture());c.speak([{id:'S01-U001',text:'source'},{id:'S01-U002',text:'source'}],null,x=>done.push(x.id));await ready(c);const first=c.audio;first.onplaying();assert.equal(states.at(-1).status,'playing');first.onended();assert.deepEqual(done,['S01-U001']);await until(()=>c.audio&&c.audio!==first);const second=c.audio;c.stop();second.onended();assert.deepEqual(done,['S01-U001']);assert.equal(states.at(-1).status,'idle');});
test('simulated HTMLAudio pause resumes same source and media errors do not advance',async()=>{const states=[],done=[];const c=new AudioController(FakeAudio,s=>states.push(s),fixture());c.speak([{id:'S01-U001',text:'source'}],null,x=>done.push(x));await ready(c);const audio=c.audio;audio.onplaying();c.pause();assert.equal(states.at(-1).status,'paused');c.resume();assert.equal(c.audio,audio);audio.onerror();audio.onended();assert.equal(done.length,0);assert.equal(states.at(-1).status,'error');});
test('selected audio integrity failure and changed source fail before playback',async()=>{for(const badSource of [false,true]){const states=[],f=fixture();if(!badSource)f.fetcher=async()=>new Response('changed',{headers:{'Content-Type':'audio/mpeg'}});const c=new AudioController(FakeAudio,s=>states.push(s),f);c.speak([{id:'S01-U001',text:badSource?'different':'source'}]);await until(()=>states.at(-1).status==='error');assert.equal(states.at(-1).status,'error');assert.equal(c.audio,null);}});
import {guardAttempt} from '../scripts/audio-guards.mjs';
test('pure synthesis guards count uncertain attempts and reject changed input, repeated IDs and cumulative caps without network',()=>{const digest='approved',record={id:'next',text:'source'};assert.doesNotThrow(()=>guardAttempt({approvedInputDigest:digest,attempts:[]},digest,record));assert.throws(()=>guardAttempt({approvedInputDigest:'changed',attempts:[]},digest,record),/changed/);assert.throws(()=>guardAttempt({approvedInputDigest:digest,attempts:[{id:'next',characters:6,outcome:'uncertain'}]},digest,record),/uncertain/);assert.throws(()=>guardAttempt({approvedInputDigest:digest,attempts:Array.from({length:120},(_,n)=>({id:String(n),characters:1}))},digest,record),/cap/);assert.throws(()=>guardAttempt({approvedInputDigest:digest,attempts:[{id:'prior',characters:29999}]},digest,record),/cap/);});
import fs from 'node:fs';import crypto from 'node:crypto';
test('complete prepared audio binds exactly117 visible guide units and3 Scripture passages to immutable source bytes',()=>{const hash=x=>crypto.createHash('sha256').update(x).digest('hex');const guide=JSON.parse(fs.readFileSync('public/content/mark-1-1-13/guide.json')),bibles=JSON.parse(fs.readFileSync('public/content/mark-1-1-13/scripture.json')),manifest=JSON.parse(fs.readFileSync('public/audio/mark-1-1-13/manifest.json'));const units=[...guide.steps.flatMap(s=>s.units).filter(u=>!/^S04-U0(1[7-9]|2[0-9])$/.test(u.id)),...bibles.map(b=>({id:`scripture-${b.resourceCode}`,text:b.verses.map(v=>v.text).join(' ')}))];assert.equal(manifest.entries.length,120);assert.equal(new Set(manifest.entries.map(e=>e.id)).size,120);for(const u of units){const e=manifest.entries.find(x=>x.id===u.id);assert.equal(e.sourceSha256,hash(u.text));const bytes=fs.readFileSync(`public${e.path}`);assert.equal(bytes.length,e.bytes);assert.equal(hash(bytes),e.sha256);}});
test('a late resume rejection cannot overwrite a stopped session',async()=>{const states=[];const c=new AudioController(FakeAudio,s=>states.push(s),fixture());c.speak([{id:'S01-U001',text:'source'}]);await ready(c);let reject;c.audio.play=()=>new Promise((_,r)=>{reject=r;});c.resume();c.stop();reject(Error('late denial'));await new Promise(r=>setTimeout(r,1));assert.equal(states.at(-1).status,'idle');});
import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
test('actual shell builder refuses missing, duplicate and source-mismatched mandatory narration manifests',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'fia-audio-gate-'));try{const dist=path.join(root,'dist');fs.mkdirSync(path.join(dist,'assets'),{recursive:true});fs.writeFileSync(path.join(dist,'index.html'),'fixture');fs.mkdirSync(path.join(dist,'content/mark-1-1-13'),{recursive:true});for(const name of ['manifest.json','guide.json','scripture.json'])fs.copyFileSync(`public/content/mark-1-1-13/${name}`,path.join(dist,'content/mark-1-1-13',name));const run=()=>spawnSync(process.execPath,[path.resolve('scripts/build-offline-shell.mjs')],{cwd:root,encoding:'utf8'});assert.match(run().stderr,/Mandatory narration manifest missing/);fs.mkdirSync(path.join(dist,'audio/mark-1-1-13'),{recursive:true});const file=path.join(dist,'audio/mark-1-1-13/manifest.json'),m=JSON.parse(fs.readFileSync('public/audio/mark-1-1-13/manifest.json'));const duplicate=structuredClone(m);duplicate.entries[1]=duplicate.entries[0];fs.writeFileSync(file,JSON.stringify(duplicate));assert.match(run().stderr,/Incomplete mandatory narration pack/);m.entries[0].sourceSha256='wrong';fs.writeFileSync(file,JSON.stringify(m));assert.match(run().stderr,/Narration source binding failed/);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('media timing follows native metadata/time events and restart reuses the recording',async()=>{const states=[];const c=new AudioController(FakeAudio,s=>states.push(s),fixture());c.speak([{id:'S01-U001',text:'source',title:'Source section',owner:'guide'}]);await ready(c);c.audio.duration=12;c.audio.currentTime=3;c.audio.onloadedmetadata();c.audio.onplaying();c.audio.ontimeupdate();assert.equal(states.at(-1).duration,12);assert.equal(states.at(-1).elapsed,3);assert.equal(states.at(-1).owner,'guide');const same=c.audio;c.restart();assert.equal(c.audio,same);assert.equal(c.audio.currentTime,0);});
