import {test,expect} from '@playwright/test';
const endQueue=async page=>{for(let i=0;i<30;i++){await expect.poll(()=>page.evaluate(()=>window.__partAudio?.readyState??0)).toBeGreaterThan(0);await page.evaluate(()=>{const a=window.__partAudio;a.currentTime=Math.max(0,a.duration-.05);if(a.paused)a.play();});await expect.poll(()=>page.evaluate(()=>window.__partAudio.ended)).toBe(true);const old=await page.evaluate(()=>window.__partCount);await page.waitForTimeout(850);if(await page.evaluate(()=>window.__partCount)===old)return;}throw Error('queue did not finish');};
for(const [language,id,step,kind] of [['eng','S02-U005','S02','resources'],['eng','S01-U002','S01','scripture'],['spa','spa-mrk-p1-v2.1-s2-u015','2','resources'],['spa','spa-mrk-p1-v2.1-s1-u003','1','scripture'],['eng','S02-U005','S02','resources-modal'],['spa','spa-mrk-p1-v2.1-s2-u015','2','resources-modal']])test(`automatic all page parts ${language} ${kind}`,async({page})=>{
 test.setTimeout(90000);await page.setViewportSize({width:390,height:987});await page.addInitScript(()=>{const Native=Audio;window.__partCount=0;window.Audio=class extends Native{constructor(...args){super(...args);window.__partAudio=this;window.__partCount++;}};localStorage.setItem('fia.media-quality.v1','original');});await page.goto('/');if(language==='spa'){await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();}
 await page.getByRole('combobox',{name:'Guide step',exact:true}).selectOption(step);await page.getByRole('button',{name:/^Section .* · Browse$/}).click();await page.getByRole('dialog').locator(`[data-unit-id="${id}"]`).click();const mark=()=>page.getByRole('button',{name:'Mark section complete',exact:true});await expect(mark()).toBeEnabled();await page.locator('.guide-footer .owner-toggle').click();await endQueue(page);await expect(mark()).toBeVisible();await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id',id);
 if(kind==='scripture'){await page.getByRole('button',{name:/^Play Scripture/}).click();await endQueue(page);}else{const tiles=page.locator('.context-resources .resource-tile');const count=await tiles.count();expect(count).toBeGreaterThan(0);for(let i=0;i<count;i++){if(kind==='resources-modal'){if(language==='eng'&&i>0)await page.getByRole('dialog').getByRole('button',{name:'Next resource',exact:true}).click();else await tiles.nth(i).getByRole('button').first().click();await page.getByRole('dialog').locator('.dialog-header-actions').getByRole('button',{name:/^Play /}).click();await endQueue(page);if(language!=='eng'||i===count-1)await page.keyboard.press('Escape');}else{await tiles.nth(i).getByRole('button',{name:/^Play /}).click();await endQueue(page);}}}
 if(kind==='resources-modal'&&language==='eng')await page.getByRole('tab',{name:'Guide',exact:true}).click();
 const undo=page.getByRole('button',{name:'Mark section incomplete',exact:true});await expect(undo).toBeVisible();await undo.click();await expect(mark()).toBeFocused();await page.locator('.guide-footer .owner-toggle').click();await endQueue(page);await expect(mark()).toBeVisible();await page.reload();await expect(mark()).toBeEnabled();await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id',id);
 await page.screenshot({path:`evidence/automatic-completion/${language}-${kind}.png`});
});
test('unrelated catalog playback does not backfill the guide page',async({page})=>{await page.addInitScript(()=>{const Native=Audio;window.__partCount=0;window.Audio=class extends Native{constructor(...a){super(...a);window.__partAudio=this;window.__partCount++;}};localStorage.setItem('fia.media-quality.v1','original');});await page.goto('/');await page.getByRole('combobox',{name:'Guide step',exact:true}).selectOption('S02');await page.getByRole('button',{name:/^Section .* · Browse$/}).click();await page.getByRole('dialog').locator('[data-unit-id="S02-U005"]').click();await page.locator('.guide-footer .owner-toggle').click();await endQueue(page);const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('fia.guide-completion.v1.eng.mark-1-1-13')).records.find(r=>r.sectionId==='S02-U005').playedParts);await page.getByRole('tab',{name:'Resources',exact:true}).click();await page.locator('.resource-tile').filter({has:page.getByRole('button',{name:'Jordan River',exact:true})}).getByRole('button',{name:'Jordan River',exact:true}).click();await page.getByRole('dialog').locator('.dialog-header-actions').getByRole('button',{name:/^Play /}).click();await endQueue(page);await page.keyboard.press('Escape');await page.getByRole('tab',{name:'Guide',exact:true}).click();await expect(page.getByRole('button',{name:'Mark section complete',exact:true})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('fia.guide-completion.v1.eng.mark-1-1-13')).records.find(r=>r.sectionId==='S02-U005').playedParts)).toEqual(before);});
