import {test,expect} from '@playwright/test';
test.use({viewport:{width:466,height:987},serviceWorkers:'block'});
const audioHash=page=>page.evaluate(async()=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await(await fetch(window.__audio.src)).arrayBuffer()))).map(x=>x.toString(16).padStart(2,'0')).join(''));
const header=page=>page.locator('.guide-card .card-players');
const target=async page=>{await page.getByLabel('Guide step').selectOption('2');await page.getByRole('button',{name:'Next guide activity',exact:true}).click();await expect(page.getByTestId('current-unit')).toContainText('El libro de Marcos comienza preparando');};
const spanish=async page=>{await page.goto('/');await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/Español/}).click();};
test('current Spanish guide action starts its clip and explicit restart; stale resource never wins',async({page})=>{
 await page.addInitScript(()=>{const A=window.Audio;window.Audio=class extends A{constructor(...args){super(...args);window.__audio=this;}};});await spanish(page);await target(page);
 const play=header(page).getByRole('button',{name:/^Play /});await expect(play).toBeEnabled();await page.screenshot({path:'evidence/guide-header-audio/initial.png'});await play.click();await expect.poll(()=>page.evaluate(()=>window.__audio?.currentTime||0)).toBeGreaterThan(.2);const current=await audioHash(page);expect(await page.evaluate(()=>JSON.parse(localStorage['fia-audio-checkpoint/spa/v1']).selection.id)).toBe('spa-mrk-p1-v2.1-s2-u012');await page.evaluate(()=>window.__audio.currentTime=5);await header(page).getByRole('button',{name:/^Restart /}).click();await expect.poll(()=>page.evaluate(()=>window.__audio.currentTime)).toBeLessThan(2);expect(await audioHash(page)).toBe(current);
 await page.getByRole('tab',{name:'Resources',exact:true}).click();await page.locator('.resource-card-actions button').first().click();await expect.poll(()=>audioHash(page)).not.toBe(current);await page.getByRole('tab',{name:'Guide',exact:true}).click();await expect(play).toBeEnabled();await play.click();await expect.poll(()=>audioHash(page)).toBe(current);
 // Restore an old guide checkpoint while current page is its successor.
 await page.evaluate(()=>{const key=Object.keys(localStorage).find(k=>k.startsWith('fia-workspace/spa/'));const state=JSON.parse(localStorage[key]);state.groupId='spa-mrk-p1-v2.1-s2-u013';localStorage[key]=JSON.stringify(state);});await page.reload();await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id','spa-mrk-p1-v2.1-s2-u013');await expect(header(page).getByRole('button',{name:/^Play /})).toBeEnabled();await header(page).getByRole('button',{name:/^Play /}).click();await expect.poll(()=>audioHash(page)).not.toBe(current);
});
test('unavailable policy retains named disabled action and English retains its current-guide action',async({page})=>{await page.goto('/');await expect(header(page).getByRole('button',{name:'Play guide',exact:true})).toBeEnabled();await spanish(page);await target(page);await page.evaluate(()=>localStorage.setItem('fia.narration.v1','aquifer-only'));await page.reload();await expect(header(page).getByRole('button',{name:/^Play /})).toBeVisible();await expect(header(page).getByRole('button',{name:/^Play /})).toBeDisabled();await page.screenshot({path:'evidence/guide-header-audio/unavailable.png'});});
