import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {completionSources,completionCatalog,validateCompletion,reduceCompletion,sectionComplete,stepComplete,readCompletion,writeCompletion,completionKey} from '../src/lib/guide-completion.js';
import {activeUnits,initialSession,canFinish} from '../src/lib/flow.js';import {spanishGuideView} from '../src/lib/guide-presentation.js';
const catalog={language:'eng',passageId:'mark-1-1-13',sections:[{id:'a',stepId:'1',sourceDigest:'a1'},{id:'b',stepId:'1',sourceDigest:'b1'},{id:'c',stepId:'2',sourceDigest:'c1'}]};const empty=()=>validateCompletion(null,catalog);
test('only explicit marks produce progress; undo changes one mark and derived step',()=>{let value=empty();for(const type of ['visit','next','audio-end','seek','finish'])value=reduceCompletion(value,{type,sectionId:'a'},catalog);assert.deepEqual(value.records,[]);value=reduceCompletion(value,{type:'mark',sectionId:'a'},catalog);assert(!stepComplete(value,'1',catalog));value=reduceCompletion(value,{type:'mark',sectionId:'b'},catalog);assert(stepComplete(value,'1',catalog));value=reduceCompletion(value,{type:'undo',sectionId:'a'},catalog);assert(!stepComplete(value,'1',catalog));assert(sectionComplete(value,'b'));});
test('legacy visits, different language, stale digest, duplicate and unknown IDs do not mark',()=>{assert.deepEqual(validateCompletion({visited:['a'],finished:true},catalog).records,[]);const marked=reduceCompletion(empty(),{type:'mark',sectionId:'a'},catalog);assert.deepEqual(validateCompletion({...marked,language:'spa'},catalog).records,[]);assert.deepEqual(validateCompletion({...marked,records:[{sectionId:'a',sourceDigest:'old'},{sectionId:'unknown',sourceDigest:'a1'}]},catalog).records,[]);assert.deepEqual(validateCompletion({...marked,records:[...marked.records,...marked.records]},catalog).records,[]);assert.deepEqual(validateCompletion({...marked,records:[...marked.records,{sectionId:'b',sourceDigest:'old'}]},catalog).records,marked.records);});
test('storage roundtrip is separate from position and reports corrupt/read/write failure',()=>{const store=new Map([['fia.session','unchanged']]),storage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},value=reduceCompletion(empty(),{type:'mark',sectionId:'a'},catalog);assert.equal(writeCompletion(storage,value),'');assert.deepEqual(readCompletion(storage,catalog).value,value);assert.equal(store.get('fia.session'),'unchanged');assert.notEqual(completionKey('eng'),completionKey('spa'));store.set(completionKey('eng'),'bad');assert.match(readCompletion(storage,catalog).warning,/could not be read/);assert.match(readCompletion(null,catalog).warning,/could not be read/);assert.match(writeCompletion({setItem(){throw Error('quota')}},value),/not saved/);});
test('source adapters exclude optional and attached aliases; digests track body/cue semantics',async()=>{const guide=JSON.parse(fs.readFileSync('public/content/mark-1-1-13/guide.json')),cues=JSON.parse(fs.readFileSync('public/content/mark-1-1-13/cues.json')),pack={guide,cues};const sources=completionSources(pack,'eng');assert.equal(sources.length,guide.steps.flatMap(s=>activeUnits(s,cues)).length);assert(!sources.some(s=>['S02-U012','S05-U044','S05-U045'].includes(s.id)));const a=await completionCatalog(sources,'eng'),changed=structuredClone(sources);changed[0].source.body[0].text+='changed';const b=await completionCatalog(changed,'eng');assert.notEqual(a.sections[0].sourceDigest,b.sections[0].sourceDigest);assert.equal(a.sections[1].sourceDigest,b.sections[1].sourceDigest);const spanish=spanishGuideView(JSON.parse(fs.readFileSync('public/content/spa/mark-1-1-13/pack.json')));const spa=completionSources(spanish,'spa');assert.equal(spa.length,spanish.guide.groups.filter(g=>g.ordinaryQueue).length);assert(!spa.some(s=>Object.keys(spanish.guide.groupAliases).includes(s.id)));const session=initialSession(guide);for(const marks of [empty(),{...empty(),records:[{sectionId:'a',sourceDigest:'a1'}]},{...empty(),records:catalog.sections.map(s=>({sectionId:s.id,sourceDigest:s.sourceDigest}))}]){assert.equal(canFinish(session,guide),false);assert.deepEqual(session,initialSession(guide));assert(marks.records.length>=0);}});

test('source revision drops removed sections but retains exact surviving marks',()=>{const old={...empty(),records:catalog.sections.map(s=>({sectionId:s.id,sourceDigest:s.sourceDigest}))};assert.deepEqual(validateCompletion(old,{...catalog,sections:catalog.sections.slice(0,1)}).records,[{sectionId:'a',sourceDigest:'a1'}]);});
