import {test,expect} from '@playwright/test';
for(const width of [319,390,726])for(const language of ['eng','spa'])for(const dark of [false,true])test(`optional completion preserves guide/audio ${width} ${language} dark=${dark}`,async({page})=>{
 await page.setViewportSize({width,height:987});await page.addInitScript(()=>{const Native=Audio;window.Audio=class extends Native{constructor(...args){super(...args);window.__completionAudio=this;}};localStorage.setItem('fia.media-quality.v1','original');});await page.goto('/');
 if(language==='spa'){await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();await expect(page.locator('[data-content-language=spa]')).toBeVisible();}
 if(dark)await page.getByRole('button',{name:'Switch to dark theme',exact:true}).click();
 const unit=page.getByTestId('current-unit'),id=await unit.getAttribute('data-unit-id'),mark=page.getByRole('button',{name:'Mark section complete',exact:true});await expect(mark).toBeEnabled();const normalBackground=await mark.evaluate(el=>getComputedStyle(el).backgroundColor);
 await page.locator('.guide-footer .owner-toggle').click();await expect.poll(()=>page.evaluate(()=>window.__completionAudio?.currentTime??0)).toBeGreaterThan(.1);await page.locator('.guide-footer .owner-toggle').click();const offset=await page.evaluate(()=>window.__completionAudio.currentTime);
 await mark.focus();await page.keyboard.press('Enter');const undo=page.getByRole('button',{name:'Mark section incomplete',exact:true});await expect(undo).toBeFocused();expect(await undo.evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(normalBackground);await expect(unit).toHaveAttribute('data-unit-id',id);expect(await page.evaluate(()=>window.__completionAudio.paused)).toBe(true);expect(await page.evaluate(()=>window.__completionAudio.currentTime)).toBeCloseTo(offset,1);
 const index=page.getByRole('button',{name:/^Section .* · Browse$/});await index.click();const row=page.locator('[data-unit-id="'+id+'"][aria-current="location"]');await expect(row).toContainText('Completed');await page.keyboard.press('Escape');await expect(index).toBeFocused();expect(await page.evaluate(()=>window.__completionAudio.currentTime)).toBeCloseTo(offset,1);
 await undo.focus();await page.screenshot({path:`evidence/automatic-completion/${width}-${language}-${dark?'dark':'light'}.png`});
 await page.reload();await expect(page.getByRole('button',{name:'Mark section incomplete',exact:true})).toBeEnabled();await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id',id);
 await page.getByRole('button',{name:'Mark section incomplete',exact:true}).click();await expect(page.getByRole('button',{name:'Mark section complete',exact:true})).toBeFocused();await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id',id);
});

import fs from 'node:fs';
import {completionSources,completionCatalog,completionKey} from '../src/lib/guide-completion.js';
import {spanishGuideView} from '../src/lib/guide-presentation.js';
const english={guide:JSON.parse(fs.readFileSync('public/content/mark-1-1-13/guide.json')),cues:JSON.parse(fs.readFileSync('public/content/mark-1-1-13/cues.json'))},spanish=spanishGuideView(JSON.parse(fs.readFileSync('public/content/spa/mark-1-1-13/pack.json')));
for(const language of ['eng','spa'])for(const mode of ['empty','partial','full'])test(`Finish remains visit-based with ${mode} explicit fixture marks ${language}`,async({page})=>{
 const catalog=await completionCatalog(completionSources(language==='eng'?english:spanish,language),language),records=(mode==='full'?catalog.sections:mode==='partial'?catalog.sections.slice(0,1):[]).map(s=>({sectionId:s.id,sourceDigest:s.sourceDigest}));
 await page.addInitScript(({key,value})=>localStorage.setItem(key,JSON.stringify(value)),{key:completionKey(language),value:{schemaVersion:1,language,passageId:catalog.passageId,records}});await page.goto('/');
 if(language==='spa'){await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();}
 const step=page.getByRole('combobox',{name:'Guide step',exact:true}),lastStep=language==='eng'?'S06':'6';
 const goLast=async()=>{await step.selectOption(lastStep);await page.getByRole('button',{name:/^Section .* · Browse$/}).click();await page.getByRole('dialog').locator('[data-unit-id]').last().click();};
 await goLast();const finish=page.getByRole('button',{name:'Finish session',exact:true});await expect(finish).toBeDisabled();
 for(let n=1;n<=6;n++)await step.selectOption(language==='eng'?`S0${n}`:String(n));await goLast();await expect(finish).toBeEnabled();
 const section=await page.getByTestId('current-unit').getAttribute('data-unit-id');await page.getByRole('button',{name:mode==='full'?'Mark section incomplete':'Mark section complete',exact:true}).click();await expect(finish).toBeEnabled();await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id',section);await finish.click();await expect(page.getByText('Session finished.',{exact:true})).toBeVisible();
});
for(const language of ['eng','spa'])test(`explicit marks derive step check and undo clears it ${language}`,async({page})=>{
 await page.goto('/');if(language==='spa'){await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();}
 for(let n=0;n<8;n++){await page.getByRole('button',{name:'Mark section complete',exact:true}).click();if(n<7)await page.getByRole('button',{name:'Next guide activity',exact:true}).click();}
 const step=page.getByRole('combobox',{name:'Guide step',exact:true});await expect(step.locator('option:checked')).toContainText('completed');await page.screenshot({path:`evidence/automatic-completion/${language}-step-completed.png`});await page.getByRole('button',{name:/^Section .* · Browse$/}).click();await page.screenshot({path:`evidence/automatic-completion/${language}-index-completed.png`});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Mark section incomplete',exact:true}).click();await expect(step.locator('option:checked')).not.toContainText('completed');
});
test('explicit marks survive saved offline reload and language roundtrip',async({page,context})=>{
 test.setTimeout(120000);await page.goto('/');
 const markAndSave=async()=>{await page.getByRole('button',{name:'Mark section complete',exact:true}).click();await page.getByRole('button',{name:'Offline passage and settings'}).click();await page.getByRole('combobox',{name:'Media quality',exact:true}).selectOption('original');await page.getByRole('button',{name:'Save for offline',exact:true}).click();await expect(page.locator('.offline-status')).toContainText('saved on this device',{timeout:60000});await page.getByRole('button',{name:'Close resource'}).click();};
 await markAndSave();await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();await markAndSave();await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^English/}).click();await expect(page.getByRole('button',{name:'Mark section incomplete',exact:true})).toBeEnabled();
 await context.setOffline(true);await page.reload();await expect(page.getByRole('button',{name:'Mark section incomplete',exact:true})).toBeEnabled();await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();await expect(page.getByRole('button',{name:'Mark section incomplete',exact:true})).toBeEnabled();
});
test('completion quota failure stays session-only and reload does not claim persistence',async({page})=>{
 await page.goto('/');const unit=page.getByTestId('current-unit'),id=await unit.getAttribute('data-unit-id');await expect(page.getByRole('button',{name:'Mark section complete',exact:true})).toBeEnabled();await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('fia.guide-completion.'))throw Error('quota fixture');return original.call(this,key,value);};});await page.getByRole('button',{name:'Mark section complete',exact:true}).click();await expect(page.getByText('Completion mark changed for this session but was not saved on this device.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Mark section incomplete',exact:true})).toBeVisible();await expect(unit).toHaveAttribute('data-unit-id',id);await page.reload();await expect(page.getByRole('button',{name:'Mark section complete',exact:true})).toBeEnabled();await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id',id);
});
