import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import crypto from'node:crypto';
const bytes=new TextEncoder().encode('test'),sha=crypto.createHash('sha256').update(bytes).digest('hex');
const variant={path:`/__fia_variants__/${sha}/${encodeURIComponent('preset=voice,q=medium,f=opus')}/${sha}.ogg`,sourcePath:'/audio/test.mp3',sourceSha256:sha,recipe:'preset=voice,q=medium,f=opus',fetchUrl:'https://proxy.test/audio/preset=voice,q=medium,f=opus/https://source.test/audio/test.mp3',bytes:4,sha256:sha,mime:'audio/ogg',group:'pack'};
function harness({corrupt=false,hold=false,badUrl=false,delayPut=false}={}){const stores=new Map(),listeners={},responses=[];let held,releasePut;const cacheApi={async open(n){if(!stores.has(n))stores.set(n,new Map());const m=stores.get(n);return{async match(k){return m.get(k)?.clone()},async put(k,v){if(delayPut&&n.startsWith('fia-stage-')&&k==='/f0')await new Promise(r=>releasePut=r);m.set(k,v.clone());},async delete(k){return m.delete(k)}}},async delete(n){return stores.delete(n)}};const manifest={schemaVersion:1,id:'mark-1-1-13',quality:'medium',sourceBase:'https://source.test',proxyBase:'https://proxy.test',revision:'new',entries:[{...variant,...(badUrl?{fetchUrl:'https://evil.test/media'}:{})},...Array.from({length:15},(_,i)=>({path:'/f'+i,bytes:4,sha256:sha,mime:'text/plain',group:i===0?'shell':'pack'}))]};
 vm.runInNewContext(fs.readFileSync('public/sw.js','utf8'),{self:{addEventListener:(n,f)=>listeners[n]=f,location:{origin:'http://fixture'},clients:{matchAll:async()=>[]}},caches:cacheApi,setTimeout,clearTimeout,Response,URL,AbortController,crypto:crypto.webcrypto,fetch:async path=>{if(path==='/offline-shell-medium.json')return new Response(JSON.stringify(manifest));throw Error('Network unavailable');}});
 const port={postMessage(v){responses.push(v);if(v.fetchEntry){const reply=()=>port.onmessage({data:{requestId:v.requestId,bytes:corrupt&&v.fetchEntry.fetchUrl?new TextEncoder().encode('evil'):bytes,mime:v.fetchEntry.mime}});if(hold&&v.fetchEntry.fetchUrl)held=reply;else queueMicrotask(reply);}}};
 return{listeners,cacheApi,responses,stores,get releasePut(){return releasePut;},get held(){return held;},async start(){const meta=await cacheApi.open('fia-meta-v1');await meta.put('/__fia_active__',new Response(JSON.stringify({cache:'old',revision:'old',quality:'medium',entries:[]})));let operation;listeners.message({data:{type:'SAVE',id:'test',quality:'medium',clientFetch:true},ports:[port],waitUntil:p=>operation=p});return{operation};}};
}
test('Medium stages progressive completions but Saved waits for final verified item; exact proxy serves cache',async()=>{const h=harness({hold:true}),{operation}=await h.start();for(let i=0;i<20&&!h.held;i++)await new Promise(r=>setTimeout(r,1));await new Promise(r=>setTimeout(r,5));assert(h.responses.some(r=>r.progress));assert(!h.responses.some(r=>r.done));h.held();await operation;assert.equal(h.responses.at(-1).saved,true);assert.equal(h.responses.at(-1).quality,'medium');const meta=await h.cacheApi.open('fia-meta-v1'),active=await(await meta.match('/__fia_active__')).json();assert(active.entries.some(e=>e.path===variant.path));let response;h.listeners.fetch({request:{method:'GET',url:variant.fetchUrl,mode:'cors'},respondWith:p=>response=p});assert.equal(await(await response).text(),'test');});
test('bad derivative hash retains prior pack and reports integrity rather than claiming canceled',async()=>{const h=harness({corrupt:true}),{operation}=await h.start();await operation;assert.equal(h.responses.at(-1).saved,false);assert.match(h.responses.at(-1).error,/Integrity/);const meta=await h.cacheApi.open('fia-meta-v1');assert.equal((await(await meta.match('/__fia_active__')).json()).cache,'old');});
test('cancel cancels pending staging and retains previous pack',async()=>{const h=harness({hold:true}),{operation}=await h.start();for(let i=0;i<20&&!h.held;i++)await new Promise(r=>setTimeout(r,1));h.listeners.message({data:{type:'CANCEL',id:'test'},ports:[]});await operation;assert.match(h.responses.at(-1).error,/canceled/i);const meta=await h.cacheApi.open('fia-meta-v1');assert.equal((await(await meta.match('/__fia_active__')).json()).cache,'old');});
test('manifest rejects arbitrary external URL before requesting bytes',async()=>{const h=harness({badUrl:true}),{operation}=await h.start();await operation;assert.match(h.responses.at(-1).error,/Unapproved/);assert(!h.responses.some(r=>r.fetchEntry));});

test('fault waits for already-started cache writes before deleting staging and cancels client queue',async()=>{const h=harness({hold:true,corrupt:true,delayPut:true}),{operation}=await h.start();for(let i=0;i<100&&!h.releasePut;i++)await new Promise(r=>setTimeout(r,1));assert(h.releasePut);h.held();await new Promise(r=>setTimeout(r,5));assert(h.responses.some(r=>r.cancelDownloads));assert(!h.responses.some(r=>r.done));h.releasePut();await operation;assert.match(h.responses.at(-1).error,/Integrity/);assert(![...h.stores.keys()].some(n=>n.startsWith('fia-stage-')));const meta=await h.cacheApi.open('fia-meta-v1');assert.equal((await(await meta.match('/__fia_active__')).json()).cache,'old');});
