import {test,expect} from '@playwright/test';
for(const [width,theme] of [[390,'light'],[390,'dark'],[320,'light']])for(const language of ['eng','spa'])test(`Offline surface ${width} ${theme} ${language}`,async({page})=>{
 await page.setViewportSize({width,height:987});await page.goto('/');if(theme==='dark')await page.getByRole('button',{name:'Switch to dark theme'}).click();
 if(language==='spa'){await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();await expect(page.locator('[data-content-language=spa]')).toBeVisible();}
 await page.getByRole('button',{name:'Offline passage and settings'}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'Offline passage',exact:true})).toBeVisible();
 for(const name of ['Narration','Media quality'])await expect(dialog.getByRole('combobox',{name,exact:true})).toBeVisible();
 const save=dialog.getByRole('button',{name:'Save for offline',exact:true});await expect(save).toBeVisible();await expect(save).toBeEnabled();expect(await save.evaluate(el=>{const b=el.getBoundingClientRect();return b.top>=0&&b.bottom<=innerHeight&&el.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2));})).toBe(true);
 await expect(dialog.locator('.offline-status')).toContainText('Not saved');await expect(dialog.getByText(/Medium .* MB · Original/)).toBeVisible();
 await expect(dialog.getByText(/AI narration uses a synthetic voice/)).not.toBeVisible();await expect(dialog.getByRole('heading',{name:'FIA on this device'})).not.toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`evidence/offline-surface/${width}-${theme}-${language}.png`});
 await dialog.getByText('More about offline saving',{exact:true}).click();await expect(dialog.getByText(/AI narration uses a synthetic voice/)).toBeVisible();await dialog.getByText('More about offline saving',{exact:true}).click();
 await dialog.getByText('Install on this device',{exact:true}).click();await expect(dialog.getByRole('heading',{name:'FIA on this device'})).toBeVisible();await dialog.getByText('Install on this device',{exact:true}).click();
 // Real UI persistence failure, with reference sections still closed.
 await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='fia.narration.v1')throw Error('test storage unavailable');return original.call(this,k,v);};});
 const select=dialog.getByRole('combobox',{name:'Narration',exact:true});await select.focus();await expect(select).toBeFocused();await page.keyboard.press('Tab');await expect(dialog.getByRole('combobox',{name:'Media quality',exact:true})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(select).toBeFocused();await select.selectOption('aquifer-only');await expect(select).toHaveValue('aquifer-only');await expect(dialog.getByText('Narration preference could not be saved on this device.')).toBeVisible();await expect(dialog.getByText(/AI narration uses a synthetic voice/)).not.toBeVisible();
 if(width===390&&theme==='light'&&language==='eng'){await save.click();await expect(dialog.locator('.offline-status')).toContainText('saved on this device',{timeout:60000});await dialog.getByText('Manage saved files',{exact:true}).click();await dialog.getByRole('button',{name:'Remove saved passage',exact:true}).click();await expect(dialog.getByRole('button',{name:'Confirm removal',exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Keep saved passage',exact:true}).click();await expect(dialog.getByRole('button',{name:'Confirm removal',exact:true})).toHaveCount(0);}
});
