import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';
test('simulated storage quota failure cannot replace the previous active pointer',async()=>{
 const stores=new Map(),listeners={};const cacheApi={async open(name){if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return {async match(key){return store.get(key)?.clone()},async put(key,value){if(name.startsWith('fia-stage-'))throw Error('QuotaExceededError');store.set(key,value.clone())},async delete(key){return store.delete(key)}}},async delete(name){return stores.delete(name)}};
 const meta=await cacheApi.open('fia-meta-v1');await meta.put('/__fia_active__',new Response(JSON.stringify({cache:'previous-fixture',revision:'previous',entries:[]})));
 const bytes=new TextEncoder().encode('test'),hash=crypto.createHash('sha256').update(bytes).digest('hex');const manifest={schemaVersion:1,id:'mark-1-1-13',revision:'fixture',entries:Array.from({length:16},(_,i)=>({path:`/file${i}`,bytes:4,sha256:hash,mime:'text/plain',group:'pack'}))};
 vm.runInNewContext(fs.readFileSync('public/sw.js','utf8'),{self:{addEventListener:(name,fn)=>listeners[name]=fn,location:{origin:'http://fixture'},clients:{matchAll:async()=>[]}},caches:cacheApi,Response,URL,AbortController,crypto:crypto.webcrypto,fetch:async path=>new Response(path==='/offline-shell.json'?JSON.stringify(manifest):bytes,{headers:{'Content-Type':path==='/offline-shell.json'?'application/json':'text/plain'}})});
 const replies=[];let operation;listeners.message({data:{type:'SAVE',id:'quota-fixture'},ports:[{postMessage:value=>replies.push(value)}],waitUntil:value=>operation=value});await operation;assert.equal(replies.at(-1).saved,false);assert.equal(replies.at(-1).previousSaved,true);assert.equal(replies.at(-1).updateAvailable,true);assert.match(replies.at(-1).error,/QuotaExceeded/);assert.equal((await(await meta.match('/__fia_active__')).json()).cache,'previous-fixture');
});
test('failure between shell and active metadata writes restores the previous shell and pack',async()=>{
 const stores=new Map(),listeners={};let failActive=false;const cacheApi={async open(name){if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return{async match(k){return store.get(k)?.clone()},async put(k,v){if(name==='fia-meta-v1'&&k==='/__fia_active__'&&failActive){failActive=false;throw Error('metadata commit failed');}store.set(k,v.clone())},async delete(k){return store.delete(k)}}},async delete(n){return stores.delete(n)}};
 const meta=await cacheApi.open('fia-meta-v1');await meta.put('/__fia_active__',new Response(JSON.stringify({cache:'old-pack',revision:'old',entries:[]})));await meta.put('/__fia_shell__',new Response(JSON.stringify({cache:'old-shell',entries:[]})));failActive=true;
 const bytes=new TextEncoder().encode('test'),hash=crypto.createHash('sha256').update(bytes).digest('hex'),manifest={schemaVersion:1,id:'mark-1-1-13',revision:'new',entries:Array.from({length:16},(_,i)=>({path:`/f${i}`,bytes:4,sha256:hash,mime:'text/plain',group:i===0?'shell':'pack'}))};
 vm.runInNewContext(fs.readFileSync('public/sw.js','utf8'),{self:{addEventListener:(n,f)=>listeners[n]=f,location:{origin:'http://fixture'},clients:{matchAll:async()=>[]}},caches:cacheApi,Response,URL,AbortController,crypto:crypto.webcrypto,fetch:async p=>new Response(p==='/offline-shell.json'?JSON.stringify(manifest):bytes,{headers:{'Content-Type':p==='/offline-shell.json'?'application/json':'text/plain'}})});
 let operation;const replies=[];listeners.message({data:{type:'SAVE',id:'commit'},ports:[{postMessage:v=>replies.push(v)}],waitUntil:v=>operation=v});await operation;assert.match(replies.at(-1).error,/metadata commit failed/);assert.equal((await(await meta.match('/__fia_active__')).json()).cache,'old-pack');assert.equal((await(await meta.match('/__fia_shell__')).json()).cache,'old-shell');
});
