import {test,expect} from '@playwright/test';import fs from 'node:fs';
const binding=JSON.parse(fs.readFileSync('evidence/spanish-visual-audio/BINDING.json')),pack=JSON.parse(fs.readFileSync('public/content/spa/mark-1-1-13/pack.json'));
const tile=(page,id)=>page.locator('#panel-resources .resource-tile').nth(pack.resourceOrder.indexOf(id));
test.beforeEach(async({page})=>{await page.addInitScript(()=>{localStorage.setItem('fia.media-quality.v1','original');const Native=Audio;window.__visualPlays=0;window.Audio=class extends Native{constructor(...args){super(...args);window.__visualAudio=this;}play(){window.__visualPlays++;return super.play();}};});await page.goto('/');await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();await expect(page.locator('[data-content-language=spa]')).toBeVisible();await page.getByRole('tab',{name:'Resources',exact:true}).click();});
test('all8 exact visual descriptions play; map and distinct sandals seek/end; source policy and written attribution remain honest',async({page})=>{
 test.setTimeout(90000);for(const source of binding.sourceOwners){const response=page.waitForResponse(r=>new URL(r.url()).pathname===source.path&&r.ok());await tile(page,source.resourceId).getByRole('button',{name:/^Play /}).click();await(await response).finished();await expect.poll(()=>page.evaluate(()=>window.__visualAudio.currentTime)).toBeGreaterThan(.1);await page.locator('.playback-dock .owner-toggle').click();expect(await page.evaluate(()=>window.__visualAudio.paused)).toBe(true);
 if(['c202','a204','ai-spa-from-a203'].includes(source.resourceId)){await page.evaluate(()=>window.__visualAudio.currentTime=window.__visualAudio.duration/2);await page.locator('.playback-dock .owner-toggle').click();await page.evaluate(()=>window.__visualAudio.currentTime=window.__visualAudio.duration-.1);await expect.poll(()=>page.evaluate(()=>window.__visualAudio.ended)).toBe(true);await tile(page,source.resourceId).getByRole('button',{name:/^Open /}).click();await expect(page.getByRole('dialog').getByText('Descripción traducida del inglés con IA',{exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toContainText(pack.media.find(m=>m.id===source.resourceId).visualNarration.text);if(source.resourceId==='c202')await expect(page.getByRole('dialog')).toContainText('Map labels remain English');await page.screenshot({path:`evidence/spanish-visual-audio/${source.resourceId}.png`});await page.keyboard.press('Escape');}
 }
 await expect(page.locator('[data-alignment-active]')).toHaveCount(0);await page.getByRole('button',{name:'Offline passage and settings'}).click();await page.getByRole('combobox',{name:'Narration',exact:true}).selectOption('aquifer-only');await page.keyboard.press('Escape');for(const source of binding.sourceOwners)await expect(tile(page,source.resourceId).getByRole('button',{name:/^Play /})).toHaveCount(0);
});
test('new visual checkpoint restores paused exact source while title-only offset is rejected',async({page})=>{
 const source=binding.sourceOwners.find(s=>s.resourceId==='c202');await tile(page,source.resourceId).getByRole('button',{name:/^Play /}).click();await expect.poll(()=>page.evaluate(()=>window.__visualAudio?.currentTime??0)).toBeGreaterThan(.1);await page.locator('.playback-dock .owner-toggle').click();await page.evaluate(()=>window.__visualAudio.currentTime=3);await page.waitForTimeout(300);await page.reload();await expect.poll(()=>page.evaluate(()=>window.__visualAudio?.currentTime??0)).toBe(3);expect(await page.evaluate(()=>window.__visualAudio.paused)).toBe(true);expect(await page.evaluate(()=>window.__visualPlays)).toBe(0);
 const old=JSON.parse(fs.readFileSync('src/data/spanish-audio-catalog.json')).historicalRequests.find(r=>r.owners.some(o=>o.ownerId===source.ownerId)),entry=JSON.parse(fs.readFileSync('public/audio/spa/manifest.json')).historicalEntries.find(e=>e.id===old.id);await page.addInitScript(({source,entry})=>localStorage.setItem('fia-audio-checkpoint/spa/v1',JSON.stringify({selection:{domain:'resources',id:source.resourceId,title:'Old title'},sourceOwnerId:source.ownerId,checkpoint:{clipId:entry.id,sourceSha256:entry.sourceSha256,outputSha256:entry.sha256,offsetSeconds:3,phase:'unfinished'}})),{source,entry});await page.reload();await expect(page.getByText('Saved Spanish audio position could not be restored. Play the selected source to continue.',{exact:true})).toBeVisible();expect(await page.evaluate(()=>window.__visualPlays)).toBe(0);
});
test('selected offline pack excludes historical audio and cold-plays a new raw fallback description',async({page,context})=>{
 test.setTimeout(90000);await page.getByRole('button',{name:'Offline passage and settings'}).click();await page.getByRole('combobox',{name:'Media quality',exact:true}).selectOption('original');await page.getByRole('button',{name:'Save for offline',exact:true}).click();await expect(page.locator('.offline-status')).toContainText('saved on this device',{timeout:60000});const active=await page.evaluate(async()=>await(await(await caches.open('fia-meta-v1')).match('/__fia_spa__')).json());for(const e of binding.sourceOwners)expect(active.entries.some(a=>a.path===e.path&&a.sha256===e.sha256)).toBe(true);for(const e of binding.historicalFiles)expect(active.entries.some(a=>a.path===e.path)).toBe(false);expect(new Set(active.entries.map(e=>e.path)).size).toBe(active.entries.length);await page.keyboard.press('Escape');await context.setOffline(true);await page.reload();const source=binding.sourceOwners.find(s=>s.resourceId==='a204');await tile(page,source.resourceId).getByRole('button',{name:/^Play /}).click();await expect.poll(()=>page.evaluate(()=>window.__visualAudio?.currentTime??0)).toBeGreaterThan(.1);
});
