import test from 'node:test';
import assert from 'node:assert/strict';
import {expandSpanish,acceptedPacket} from '../scripts/expand-spanish.mjs';
import {hash} from '../scripts/project-spanish.mjs';
const fixture=()=>{
 const original={terms:Array.from({length:17},(_,i)=>({id:`spa-t${i}`,originalHtml:'original'})),media:Array.from({length:5},(_,i)=>({id:`m${i}`})),scripture:[{id:'original-one'},{id:'original-two'}],supplements:Array.from({length:8},(_,i)=>({id:`s${i}`})),guide:{unchanged:true},derivedAssociations:[{resourceIds:['spa-t0']}],readiness:{audio:'unavailable'}};
 const resourceMap=[...original.terms.slice(0,15),...original.media].map(r=>({englishId:`eng-${r.id}`,spanishId:r.id}));
 const resources=Array.from({length:12},(_,i)=>{const englishId=`eng-new${i}`,body='<p>Texto</p>',title='Título';resourceMap.push({englishId,spanishId:null,englishBodySha256:hash('<p>Text</p>')});return {id:`ai-spa-from-${englishId}`,englishId,kind:'term',language:'spa',title,body,label:'Traducción con IA',notice:'AI translation',provenance:{sourceHtml:'<p>Text</p>',sourceHtmlSha256:hash('<p>Text</p>'),translatedBodySha256:hash(body),translatedTitleSha256:hash(title),rights:{licenseInfo:{}},source:{}}};});
 const scripture={supplements:['BereanStandardBible','unfoldingWordLiteral','unfoldingWordSimplified'].map(englishEdition=>({id:`ai-spa-from-${englishEdition}-mark-1-1-13`,englishEdition,label:'Traducción con IA',changeNotice:'Derived, not official',sourceRights:{licenseInfo:{}},outputLicense:{name:'CC0'},officialSpanishEdition:false,verses:Array.from({length:13},(_,i)=>({verse:i+1,text:'Texto',source:{content:'<p>Text</p>',text:'Text'},outputTextSha256:hash('Texto'),sourceHtmlSha256:hash('<p>Text</p>'),sourceTextSha256:hash('Text')}))}))};
 const options={resourceRaw:JSON.stringify(resources),scriptureRaw:JSON.stringify(scripture),resourceMap};
 for(const type of ['resource','scripture'])options[type+'Receipt']={status:'accepted',reviewer:'synthetic fixture only',sha256:hash(options[type+'Raw'])};
 return {original,options};
};
test('synthetic expansion preserves original objects, full union and unavailable audio',()=>{const{original,options}=fixture(),before=structuredClone(original),out=expandSpanish(original,options);assert.deepEqual(original,before);assert.equal(out.terms[0],original.terms[0]);assert.equal(out.supplements,original.supplements);assert.equal(out.guide,original.guide);assert.equal(out.derivedAssociations,original.derivedAssociations);assert.equal(out.resourceOrder.length,34);assert.equal(out.scripture.length,5);assert(out.scripture.slice(2).every(s=>s.verses.length===13&&!s.audio.available));assert.equal(out.audioFirstComplete,false);});
test('pending or changed packet cannot project',()=>{assert.throws(()=>acceptedPacket('[]',{status:'pending',sha256:hash('[]')}));const{original,options}=fixture();options.resourceRaw+=' ';assert.throws(()=>expandSpanish(original,options),/acceptance/);});
test('independent packet integrity and membership checks survive a matching packet receipt',()=>{for(const mutate of [r=>r[0].body+='changed',r=>r[0].id=r[1].id,r=>r[0].kind='map']){const{original,options}=fixture(),r=JSON.parse(options.resourceRaw);mutate(r);options.resourceRaw=JSON.stringify(r);options.resourceReceipt.sha256=hash(options.resourceRaw);assert.throws(()=>expandSpanish(original,options));}const{original,options}=fixture(),s=JSON.parse(options.scriptureRaw);s.supplements[0].verses.pop();options.scriptureRaw=JSON.stringify(s);options.scriptureReceipt.sha256=hash(options.scriptureRaw);assert.throws(()=>expandSpanish(original,options),/verse/);});
