import {test,expect} from '@playwright/test';import fs from 'node:fs';
const binding=JSON.parse(fs.readFileSync('evidence/spanish-visual-audio/BINDING.json')),pack=JSON.parse(fs.readFileSync('public/content/spa/mark-1-1-13/pack.json'));
const tile=(page,id)=>page.locator('#panel-resources .resource-tile').nth(pack.resourceOrder.indexOf(id));
test.beforeEach(async({page})=>{await page.addInitScript(()=>{const Native=Audio;window.__visualPlays=0;window.Audio=class extends Native{constructor(...args){super(...args);window.__visualAudio=this;}play(){window.__visualPlays++;return super.play();}};});await page.goto('/');await page.getByRole('tab',{name:'Languages',exact:true}).click();await page.getByRole('button',{name:/^Español/}).click();await expect(page.locator('[data-content-language=spa]')).toBeVisible();await page.getByRole('tab',{name:'Resources',exact:true}).click();});
test('all8 exact visual descriptions play; map and distinct sandals seek/end; source policy and written attribution remain honest',async({page})=>{
 test.setTimeout(90000);for(const source of binding.sourceOwners){const response=page.waitForResponse(r=>r.url().includes('/audio/preset=voice,q=medium,f=opus/')&&r.url().includes(source.path)&&r.ok());await tile(page,source.resourceId).getByRole('button',{name:/^Play /}).click();await(await response).finished();await expect.poll(()=>page.evaluate(()=>window.__visualAudio.currentTime)).toBeGreaterThan(.1);await page.locator('.playback-dock .owner-toggle').click();expect(await page.evaluate(()=>window.__visualAudio.paused)).toBe(true);
 if(['c202','a204','ai-spa-from-a203'].includes(source.resourceId)){await page.evaluate(()=>window.__visualAudio.currentTime=window.__visualAudio.duration/2);await page.locator('.playback-dock .owner-toggle').click();await page.evaluate(()=>window.__visualAudio.currentTime=window.__visualAudio.duration-.1);await expect.poll(()=>page.evaluate(()=>window.__visualAudio.ended)).toBe(true);await tile(page,source.resourceId).getByRole('button',{name:/^Open /}).click();await expect(page.getByRole('dialog').getByText('Descripción traducida del inglés con IA',{exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toContainText(pack.media.find(m=>m.id===source.resourceId).visualNarration.text);if(source.resourceId==='c202')await expect(page.getByRole('dialog')).toContainText('Map labels remain English');await page.keyboard.press('Escape');}
 }
 await expect(page.locator('[data-alignment-active]')).toHaveCount(0);await page.getByRole('button',{name:'Offline passage and settings'}).click();await page.getByRole('combobox',{name:'Narration',exact:true}).selectOption('aquifer-only');await page.keyboard.press('Escape');for(const source of binding.sourceOwners)await expect(tile(page,source.resourceId).getByRole('button',{name:/^Play /})).toHaveCount(0);
});
test('selected offline pack excludes historical audio and cold-plays a new Medium description',async({page,context})=>{
 test.setTimeout(90000);await page.getByRole('button',{name:'Offline passage and settings'}).click();await page.getByRole('combobox',{name:'Media quality',exact:true}).selectOption('medium');await page.getByRole('button',{name:'Save for offline',exact:true}).click();await expect(page.locator('.offline-status')).toContainText('saved on this device',{timeout:60000});const active=await page.evaluate(async()=>await(await(await caches.open('fia-meta-v1')).match('/__fia_spa__')).json());for(const e of binding.sourceOwners)expect(active.entries.some(a=>a.originalPath===e.path&&a.sha256!==e.sha256)).toBe(true);for(const e of binding.historicalFiles)expect(active.entries.some(a=>a.path===e.path)).toBe(false);expect(new Set(active.entries.map(e=>e.path)).size).toBe(active.entries.length);const checked=await page.evaluate(async()=>{const m=await(await(await caches.open('fia-meta-v1')).match('/__fia_spa__')).json(),c=await caches.open(m.cache);const rows=[];for(const e of m.entries.filter(e=>e.originalPath?.includes('/visual-description-'))){const b=await(await c.match(e.path)).arrayBuffer();rows.push({path:e.path,valid:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),v=>v.toString(16).padStart(2,'0')).join('')===e.sha256,rawSaved:!!await c.match(e.originalPath)});}return rows;});expect(checked).toHaveLength(8);expect(checked.every(e=>e.valid&&!e.rawSaved)).toBe(true);await page.evaluate(()=>{const prior=window.fetch;window.fetch=(input,options)=>String(input).includes('visual-description-c202.mp3')?Promise.resolve(new Response('corrupt',{headers:{'Content-Type':'audio/ogg'}})):prior(input,options);});await page.getByRole('button',{name:/^(Verify and save again|Update saved passage)$/}).click();await expect(page.getByRole('alert')).toContainText('previous verified pack',{timeout:30000});const after=await page.evaluate(async()=>await(await(await caches.open('fia-meta-v1')).match('/__fia_spa__')).json());expect(after).toEqual(active);await page.keyboard.press('Escape');await context.setOffline(true);await page.reload();const source=binding.sourceOwners.find(s=>s.resourceId==='a204');await tile(page,source.resourceId).getByRole('button',{name:/^Play /}).click();await expect.poll(()=>page.evaluate(()=>window.__visualAudio?.currentTime??0)).toBeGreaterThan(.1);
});
