import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import index from '../src/data/spanish-alignment.json' with {type:'json'};
import {validSpanishAlignment,spanishAlignmentOwned,spanishAlignmentPosition} from '../src/lib/spanish-alignment.js';
import {resolveMedia} from '../src/lib/media-variants.js';
const pack=JSON.parse(fs.readFileSync('public/content/spa/mark-1-1-13/pack.json')),audio=JSON.parse(fs.readFileSync('public/audio/spa/manifest.json'));
test('only three exact RV1909 verse mappings validate and source edits fail closed',()=>{assert.equal(index.length,3);for(const d of index){const data=JSON.parse(fs.readFileSync('public'+d.path)),verse=pack.scripture.find(b=>b.id==='ReinaValera1909').verses[d.verse-1],text=data.verses[0].text;assert(validSpanishAlignment(data,d,verse,text));assert(!validSpanishAlignment(data,d,{...verse,bodySha256:'bad'},text));assert(!validSpanishAlignment(data,d,verse,text+' changed'));}});
test('active exact output identity is required, including during restore and source switches',()=>{const d=index[0],data=JSON.parse(fs.readFileSync('public'+d.path));const state={status:'playing',sourceDomain:'scripture',sourceOwnerId:d.ownerId,sourceId:d.id,outputSha256:d.audioSha256,elapsed:.2};assert.equal(spanishAlignmentPosition(data,d,state).word,0);for(const change of [{outputSha256:undefined},{outputSha256:'opus'},{sourceId:'other'},{sourceOwnerId:'other'},{status:'restoring'}])assert.equal(spanishAlignmentPosition(data,d,{...state,...change}),null);assert.equal(spanishAlignmentPosition(data,d,{...state,status:'paused'}).status,'paused');assert.equal(spanishAlignmentPosition(data,d,{...state,elapsed:0}),null);assert.equal(spanishAlignmentPosition(data,d,{...state,elapsed:data.verses[0].end}),null);assert(spanishAlignmentOwned(d,{...state,elapsed:0}));assert(spanishAlignmentOwned(d,{...state,elapsed:data.duration}));for(const change of [{outputSha256:undefined},{outputSha256:'opus'},{sourceId:'other'},{sourceOwnerId:'other'}])assert(!spanishAlignmentOwned(d,{...state,...change}));});
test('Medium uses exact timed originals while prior compressed checkpoints remain safely resumable without timing',()=>{for(const d of index){const source=audio.entries.find(e=>e.id===d.id);assert.equal(resolveMedia(source,'medium').expectedDescriptor.sha256,d.audioSha256);assert.equal(resolveMedia({...source,sha256:'different'},'medium').expectedDescriptor.sha256,'different');}const untimed=audio.entries.find(e=>!index.some(d=>d.id===e.id)&&resolveMedia(e,'medium').variant==='medium');assert(untimed,'untimed existing derivatives remain selected');});

test('previously saved compressed-only payload remains playable without original timing',()=>{const d=index[0],source=audio.entries.find(e=>e.id===d.id),catalog=JSON.parse(fs.readFileSync('src/data/media-derivatives.json')),variant=catalog.entries.find(e=>e.sourceSha256===d.audioSha256&&e.eligible);assert(variant);const selected=resolveMedia(source,'medium',{offline:true,availableSha256:[variant.sha256]});assert.equal(selected.expectedDescriptor.sha256,variant.sha256);assert.equal(resolveMedia(source,'medium',{outputSha256:variant.sha256}).expectedDescriptor.sha256,variant.sha256);});
