import {test,expect} from '@playwright/test';
test.use({baseURL:'http://127.0.0.1:4185',serviceWorkers:'allow'});
test.beforeEach(async({page,request})=>{await request.post('/__test__/mode',{data:'normal'});await page.goto('/');await page.getByText('Offline passage · Not saved',{exact:true}).click();await expect(page.locator('.offline-status')).toContainText('Not saved');});
test('actual verified save survives a fresh offline page and reads every required file',async({page,context})=>{
 await page.getByRole('button',{name:'Save for offline',exact:true}).click();await expect(page.locator('.offline-status')).toContainText('Saved on this device',{timeout:20000});
 const manifest=await page.evaluate(()=>fetch('/offline-shell.json').then(r=>r.json()));await context.setOffline(true);await page.close();const cold=await context.newPage();await cold.goto('/');await expect(cold.getByTestId('current-unit')).toBeVisible();await expect(cold.locator('.offline-status')).toContainText('Saved on this device');
 const result=await cold.evaluate(async entries=>{const rows=[];for(const entry of entries){const r=await fetch(entry.path);const bytes=await r.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');rows.push({path:entry.path,ok:r.ok&&bytes.byteLength===entry.bytes&&hash===entry.sha256});}return rows;},manifest.entries);expect(result.every(r=>r.ok)).toBe(true);
 await cold.getByRole('button',{name:'Scripture',exact:true}).click();await expect(cold.locator('.scripture-text [lang="en"] > span')).toHaveCount(13);await cold.evaluate(()=>document.fonts.ready);await cold.locator('.scripture-text').scrollIntoViewIfNeeded();await cold.screenshot({path:'evidence/b3/offline-scripture-fallback.png'});
 await cold.getByRole('button',{name:'Resources',exact:true}).click();for(const img of await cold.locator('.preview-integrity-probe').all())await expect.poll(()=>img.evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);
 await cold.getByRole('button',{name:'Open Locations in the Book of Mark map'}).click();await expect.poll(()=>cold.getByRole('dialog').getByRole('img').evaluate(i=>i.naturalWidth)).toBe(3000);await cold.screenshot({path:'evidence/b3/offline-map.png'});
});
test('injected missing/corrupt transfer and cancellation preserve the previous verified pack',async({page,request})=>{
 await page.getByRole('button',{name:'Save for offline',exact:true}).click();await expect(page.locator('.offline-status')).toContainText('Saved on this device',{timeout:20000});
 for(const mode of ['missing','corrupt','delay']){await request.post('/__test__/mode',{data:mode});await page.getByRole('button',{name:'Verify and save again'}).focus();await page.keyboard.press('Enter');if(mode==='delay'){await expect(page.getByRole('button',{name:'Cancel save'})).toBeVisible();await page.getByRole('button',{name:'Cancel save'}).click();}await expect(page.getByRole('alert')).toContainText('previous verified pack',{timeout:20000});await expect(page.locator('.offline-status')).toContainText('Saved on this device');}
 await request.post('/__test__/mode',{data:'normal'});await page.getByRole('button',{name:'Check saved files'}).click();await expect(page.locator('.offline-status')).toContainText('Saved on this device');
});
test('actual cached corruption is detected and selected removal preserves the shell',async({page,context})=>{
 await page.getByRole('button',{name:'Save for offline',exact:true}).click();await expect(page.locator('.offline-status')).toContainText('Saved on this device',{timeout:20000});
 await page.evaluate(async()=>{const meta=await caches.open('fia-meta-v1'),active=await(await meta.match('/__fia_active__')).json();await(await caches.open(active.cache)).put('/assets/mark-1-1-13/a112.jpg',new Response('corrupt',{headers:{'Content-Type':'image/jpeg'}}));});await page.getByRole('button',{name:'Check saved files'}).click();await expect(page.getByRole('alert')).toContainText('Integrity failed');
 await page.getByRole('button',{name:'Save for offline',exact:true}).click();await expect(page.locator('.offline-status')).toContainText('Saved on this device',{timeout:20000});await page.getByRole('button',{name:'Remove saved passage'}).click();await page.getByRole('button',{name:'Confirm removal'}).click();await expect(page.locator('.offline-status')).toContainText('Not saved');
 const counts=await page.evaluate(async()=>{const meta=await caches.open('fia-meta-v1');return {active:!!await meta.match('/__fia_active__'),shell:!!await meta.match('/__fia_shell__')};});expect(counts).toEqual({active:false,shell:true});await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'The passage could not be opened'})).toBeVisible();
});
