import {test,expect} from '@playwright/test';
test.use({baseURL:'http://127.0.0.1:4185',serviceWorkers:'allow'});
const settings=page=>page.getByRole('button',{name:'Offline passage and settings'}).click();
async function save(page){await settings(page);await page.getByRole('button',{name:/^(Save for offline|Verify and save again)$/}).click();await expect(page.locator('.offline-status')).toContainText('Saved on this device',{timeout:60000});await page.getByRole('button',{name:'Close resource'}).click();}
test.beforeEach(async({page,request})=>{await request.post('/__test__/mode',{data:'normal'});await page.goto('/');});
test('complete offline pack and real media survive cold page, exploration and new owner',async({page,context})=>{
 await save(page);const manifest=await page.evaluate(()=>fetch('/offline-shell.json').then(r=>r.json()));await context.setOffline(true);await page.close();page=await context.newPage();await page.goto('/');
 const ok=await page.evaluate(async entries=>{for(const e of entries){const r=await fetch(e.path),b=await r.arrayBuffer(),h=[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');if(!r.ok||b.byteLength!==e.bytes||h!==e.sha256)return false;}return true;},manifest.entries);expect(ok).toBe(true);
 await page.getByRole('tab',{name:'Scripture',exact:true}).click();await page.getByRole('button',{name:'Play Scripture BSB',exact:true}).click();await expect(page.getByRole('button',{name:'Pause Now playing'})).toBeVisible();await expect.poll(()=>page.locator('.app-content :is(.card-transport-footer,.playback-dock)>.compact-transport progress').getAttribute('value')).not.toBe('0');
 await page.getByRole('tab',{name:'Resources',exact:true}).click();await expect(page.getByRole('button',{name:'Pause Now playing'})).toBeVisible();await page.getByRole('button',{name:'Open Locations in the Book of Mark map'}).click();await expect.poll(()=>page.getByRole('dialog').getByRole('img').evaluate(i=>i.naturalWidth)).toBe(3000);await page.getByRole('button',{name:'Pause Now playing'}).click();await expect(page.getByRole('button',{name:'Resume Now playing'})).toBeVisible();await page.getByRole('button',{name:'Resume Now playing'}).click();await page.getByRole('button',{name:'Close resource'}).click();
 await page.getByRole('button',{name:'Play heaven',exact:true}).click();await page.getByRole('button',{name:'Open heaven term',exact:true}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:'heaven'})).toBeVisible();await expect(page.getByRole('button',{name:'Pause Now playing'})).toBeVisible();await expect.poll(()=>page.getByRole('dialog').locator('progress').getAttribute('value')).not.toBe('0');await page.getByRole('button',{name:'Restart heaven'}).click();await page.screenshot({path:'evidence/contextual-playback/offline-term.png'});
});
test('missing corrupt canceled transfers preserve a verified pack and removal remains explicit',async({page,request,context})=>{
 await save(page);await settings(page);
 for(const mode of ['missing','corrupt','delay']){await request.post('/__test__/mode',{data:mode});await page.getByRole('button',{name:'Verify and save again'}).focus();await page.keyboard.press('Enter');if(mode==='delay'){await expect(page.getByRole('button',{name:'Cancel save'})).toBeVisible();await page.getByRole('button',{name:'Cancel save'}).click();}await expect(page.getByRole('alert')).toContainText('previous verified pack',{timeout:30000});}
 await request.post('/__test__/mode',{data:'normal'});await page.getByRole('button',{name:'Check saved files'}).click();await expect(page.getByRole('alert')).toHaveCount(0);await page.evaluate(async()=>{const m=await caches.open('fia-meta-v1'),a=await(await m.match('/__fia_active__')).json();await(await caches.open(a.cache)).put('/assets/mark-1-1-13/a112.jpg',new Response('bad',{headers:{'Content-Type':'image/jpeg'}}));});await page.getByRole('button',{name:'Check saved files'}).click();await expect(page.getByRole('alert')).toContainText('Integrity failed');await page.getByRole('button',{name:'Remove saved passage'}).click();await page.getByRole('button',{name:'Confirm removal'}).click();await expect(page.locator('.offline-status')).toContainText('Not saved');await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'The passage could not be opened'})).toBeVisible();
});
test('combined transition plays offline and stops on the activity; source info returns focus',async({page,context})=>{await page.addInitScript(()=>{const Native=window.Audio;window.__audio=[];window.Audio=class extends Native{constructor(...args){super(...args);window.__audio.push(this);}};});await save(page);await context.setOffline(true);await page.reload();await page.getByLabel('Guide step').selectOption('S06');for(let n=0;n<3;n++)await page.getByRole('button',{name:'Next guide activity',exact:true}).click();await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id','S06-U004');const paths=[];page.on('request',r=>paths.push(r.url()));await page.getByRole('button',{name:'Play guide',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.__audio.at(-1)?.duration||0)).toBeGreaterThan(0);expect(paths.some(p=>p.includes('/activity-transitions/S06-U004-with-pause.mp3'))).toBe(true);await page.evaluate(()=>{const a=window.__audio.at(-1);a.currentTime=a.duration-.1;});await expect.poll(()=>page.evaluate(()=>window.__audio.at(-1)?.ended)).toBe(true);await expect(page.getByTestId('current-unit')).toHaveAttribute('data-unit-id','S06-U004');const info=page.getByRole('button',{name:'Read complete guide and attribution'});await info.click();await expect(page.getByRole('dialog')).toContainText('Original guide text');await page.keyboard.press('Escape');await expect(info).toBeFocused();});
