import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {restoreWorkspace,WORKSPACE_KEY,storedTheme,guideRestoreQueue} from '../src/lib/workspace.js';import {approvedAudioManifest,AudioController}from'../src/lib/audio.js';import crypto from'node:crypto';
const pack={guide:JSON.parse(fs.readFileSync('public/content/mark-1-1-13/guide.json')),cues:JSON.parse(fs.readFileSync('public/content/mark-1-1-13/cues.json')),resources:JSON.parse(fs.readFileSync('public/content/mark-1-1-13/resources.json'))};
const store=value=>({getItem:key=>key===WORKSPACE_KEY?JSON.stringify(value):null});
test('workspace validates fields independently and source identity without guessing newer schemas',()=>{let v={schemaVersion:2,passage:'mark-1-1-13',theme:'dark',view:'resources',resources:{query:'x'.repeat(400),filter:'bad',selectedId:'a112',collectionIds:['a112','a112','wrong']},audio:{clipId:approvedAudioManifest.entries[0].id,sourceSha256:'changed',outputSha256:'bad',offsetSeconds:Infinity,phase:'unfinished',ownerDomain:'guide'}};let s=restoreWorkspace(store(v),pack);assert.equal(s.theme,'dark');assert.equal(s.resources.query.length,200);assert.equal(s.resources.filter,'all');assert.deepEqual(s.resources.collectionIds,['a112']);assert.equal(s.audio,null);assert.equal(restoreWorkspace(store({...v,schemaVersion:99}),pack).theme,'light');assert.equal(storedTheme({getItem(){throw Error('denied')}}),'light');});
test('restored guide queues respect source stops and reject hidden/pure metadata IDs',()=>{const session=restoreWorkspace(store(null),pack).session;assert.equal(guideRestoreQueue(pack,session,'S03-U007').length,1);assert.equal(guideRestoreQueue(pack,session,'S04-U017').length,0);assert.equal(guideRestoreQueue(pack,session,'S05-U045').length,0);});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const bytes=Buffer.from('fixture');const entry={id:'a',path:'/a',sourceSha256:hash('text'),sha256:hash(bytes),bytes:bytes.length};const item={id:'a',text:'text',owner:'guide',title:'source'};const saved={clipId:'a',sourceSha256:entry.sourceSha256,outputSha256:entry.sha256,offsetSeconds:4,phase:'unfinished'};const tick=()=>new Promise(r=>setTimeout(r,100));
class FakeAudio{static all=[];constructor(){this.listeners={};this.currentTime=0;this.duration=10;this.readyState=0;this.plays=0;FakeAudio.all.push(this)}addEventListener(n,f){(this.listeners[n]??=[]).push(f)}fire(n){this.readyState=n==='loadedmetadata'?1:this.readyState;this.listeners[n]?.forEach(f=>f());this['on'+n]?.()}load(){}play(){this.plays++;this.onplaying?.();return Promise.resolve()}pause(){this.onpause?.()}removeAttribute(){}}
function controller(fetcher=async()=>({ok:true,headers:{get:()=> 'audio/mpeg'},arrayBuffer:async()=>bytes})){return new AudioController(FakeAudio,()=>{},{manifest:{entries:[entry]},fetcher,urlApi:{createObjectURL:()=> 'blob:x',revokeObjectURL(){}}});}
test('restore never plays before explicit Resume and clamps verified metadata offset',async()=>{let c=controller();c.restore([item],saved);await tick();let a=c.audio;assert.equal(a.plays,0);a.fire('loadedmetadata');await tick();assert.equal(c.status,'paused');assert.equal(a.currentTime,4);assert.equal(a.playbackRate,.95);assert.equal(a.plays,0);c.resume();assert.equal(a.plays,1);c.stop();});
test('stale delayed fetch and metadata cannot override new playback, Restart or superseding restore',async()=>{let resolve;const c=controller(()=>new Promise(r=>resolve=r));c.restore([item],saved);await tick();c.stop();resolve({ok:true,headers:{get:()=> 'audio/mpeg'},arrayBuffer:async()=>bytes});await tick();assert.equal(c.audio,null);const d=controller();d.restore([item],saved);await tick();const stale=d.audio;d.restart();await tick();const current=d.audio;stale.fire('loadedmetadata');await tick();assert.equal(d.audio,current);assert.equal(current.plays,1);assert.equal(stale.plays,0);d.restore([item],saved);await tick();const replacement=d.audio;current.fire('loadedmetadata');replacement.fire('loadedmetadata');await tick();assert.equal(d.audio,replacement);assert.equal(replacement.plays,0);d.stop();});
