import test,{after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {restoreWorkspace,WORKSPACE_KEY,storedTheme,guideRestoreQueue} from '../src/lib/workspace.js';import {approvedAudioManifest,AudioController}from'../src/lib/audio.js';import crypto from'node:crypto';
const pack={guide:JSON.parse(fs.readFileSync('public/content/mark-1-1-13/guide.json')),cues:JSON.parse(fs.readFileSync('public/content/mark-1-1-13/cues.json')),resources:JSON.parse(fs.readFileSync('public/content/mark-1-1-13/resources.json'))};
const store=value=>({getItem:key=>key===WORKSPACE_KEY?JSON.stringify(value):null});
test('workspace validates fields independently and source identity without guessing newer schemas',()=>{let v={schemaVersion:2,passage:'mark-1-1-13',theme:'dark',view:'resources',resources:{query:'x'.repeat(400),filter:'bad',selectedId:'a112',collectionIds:['a112','a112','wrong']},audio:{clipId:approvedAudioManifest.entries[0].id,sourceSha256:'changed',outputSha256:'bad',offsetSeconds:Infinity,phase:'unfinished',ownerDomain:'guide'}};let s=restoreWorkspace(store(v),pack);assert.equal(s.theme,'dark');assert.equal(s.resources.query.length,200);assert.equal(s.resources.filter,'all');assert.deepEqual(s.resources.collectionIds,['a112']);assert.equal(s.audio,null);assert.equal(restoreWorkspace(store({...v,schemaVersion:99}),pack).theme,'light');assert.equal(storedTheme({getItem(){throw Error('denied')}}),'light');});
test('restored guide queues respect source stops and reject hidden/pure metadata IDs',()=>{const session=restoreWorkspace(store(null),pack).session;assert.equal(guideRestoreQueue(pack,session,'S03-U007').length,1);assert.equal(guideRestoreQueue(pack,session,'S04-U017').length,0);assert.equal(guideRestoreQueue(pack,session,'S05-U045').length,0);});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const bytes=Buffer.from('fixture');const entry={id:'a',path:'/a',sourceSha256:hash('text'),sha256:hash(bytes),bytes:bytes.length};const item={id:'a',text:'text',owner:'guide',title:'source'};const saved={clipId:'a',sourceSha256:entry.sourceSha256,outputSha256:entry.sha256,offsetSeconds:4,phase:'unfinished'};const until=async(predicate,label)=>{const deadline=Date.now()+5000;while(!predicate()){if(Date.now()>deadline)throw Error(`Timed out waiting for ${label}`);await new Promise(r=>setImmediate(r));}};
let pendingDigests=0;const originalDigest=globalThis.crypto.subtle.digest;globalThis.crypto.subtle.digest=async function(...args){pendingDigests++;try{return await originalDigest.apply(this,args);}finally{pendingDigests--;}};after(()=>{globalThis.crypto.subtle.digest=originalDigest;});
class FakeAudio{static all=[];constructor(){this.listeners={};this.currentTime=0;this.duration=10;this.readyState=0;this.plays=0;FakeAudio.all.push(this)}addEventListener(n,f){(this.listeners[n]??=[]).push(f)}fire(n){this.readyState=n==='loadedmetadata'?1:this.readyState;this.listeners[n]?.forEach(f=>f());this['on'+n]?.()}load(){}play(){this.plays++;this.onplaying?.();return Promise.resolve()}pause(){this.onpause?.()}removeAttribute(){}}
function controller(fetcher=async()=>({ok:true,headers:{get:()=> 'audio/mpeg'},arrayBuffer:async()=>bytes})){return new AudioController(FakeAudio,()=>{},{manifest:{entries:[entry]},fetcher,urlApi:{createObjectURL:()=> 'blob:x',revokeObjectURL(){}}});}
test('restore never plays before explicit Resume and clamps verified metadata offset',async()=>{let c=controller();c.restore([item],saved);await until(()=>!!c.audio,'restored audio allocation');let a=c.audio;assert.equal(a.plays,0);a.fire('loadedmetadata');await until(()=>c.status==='paused','metadata readiness');assert.equal(c.status,'paused');assert.equal(a.currentTime,4);assert.equal(a.playbackRate,.95);assert.equal(a.plays,0);c.resume();assert.equal(a.plays,1);c.stop();});
test('stale delayed fetch and metadata cannot override new playback, Restart or superseding restore',async()=>{let resolve,bodyRead=false;const c=controller(()=>new Promise(r=>resolve=r));c.restore([item],saved);await until(()=>!!resolve,'delayed fetch start');c.stop();resolve({ok:true,headers:{get:()=> 'audio/mpeg'},arrayBuffer:async()=>{bodyRead=true;return bytes;}});await until(()=>bodyRead&&pendingDigests===0,'stale response digest completion');await Promise.resolve();assert.equal(c.audio,null);const d=controller();d.restore([item],saved);await until(()=>!!d.audio,'first metadata waiter');const stale=d.audio;d.restart();await until(()=>!!d.audio&&d.audio!==stale&&d.audio.plays===1,'Restart replacement playback');const current=d.audio;stale.fire('loadedmetadata');await Promise.resolve();await Promise.resolve();assert.equal(d.audio,current);assert.equal(current.plays,1);assert.equal(stale.plays,0);d.restore([item],saved);await until(()=>!!d.audio&&d.audio!==current,'superseding restore');const replacement=d.audio;current.fire('loadedmetadata');replacement.fire('loadedmetadata');await until(()=>d.status==='paused','replacement metadata readiness');assert.equal(d.audio,replacement);assert.equal(replacement.plays,0);d.stop();});
test('pagehide-style checkpoint preserves source-bound offset through delayed metadata and seek',async()=>{const c=controller();c.restore([item],saved);await until(()=>!!c.audio,'metadata-pending element');const a=c.audio;assert.equal(a.currentTime,0);const pagehide=()=>JSON.parse(JSON.stringify(c.checkpoint()));assert.equal(pagehide().offsetSeconds,4);assert.equal(pagehide().clipId,saved.clipId);a.seeking=true;a.fire('loadedmetadata');await until(()=>a.currentTime===4,'seek request');a.currentTime=0;assert.equal(pagehide().offsetSeconds,4);assert.equal(a.plays,0);a.currentTime=4;a.seeking=false;a.fire('seeked');await until(()=>c.status==='paused','seek completion');assert.equal(pagehide().offsetSeconds,4);a.currentTime=5;assert.equal(pagehide().offsetSeconds,5);assert.equal(a.plays,0);c.stop();assert.equal(c.checkpoint(),null);});
