import {pageParts} from '../lib/completion-parts.js';
import {useEffect,useRef,useState} from 'react';
import {completionSources,completionCatalog,readCompletion,writeCompletion,reduceCompletion,sectionComplete,stepComplete} from '../lib/guide-completion.js';
export default function useGuideCompletion(pack,language){
 const [state,setState]=useState({catalog:null,value:null,warning:''}),current=useRef(state);current.current=state;
 useEffect(()=>{let active=true;completionCatalog(completionSources(pack,language),language).then(catalog=>{for(const section of catalog.sections)section.allowedParts=[...new Set(pack.scripture.flatMap(edition=>pageParts(pack,language,section.id,language==='eng'?edition.resourceCode:edition.id,{playable:false})))];if(!active)return;let loaded;try{loaded=readCompletion(globalThis.localStorage,catalog);}catch{loaded=readCompletion(null,catalog);}const next={catalog,...loaded};current.current=next;setState(next);}).catch(()=>{if(active)setState({catalog:null,value:null,warning:'Completion marks are unavailable for this source.'});});return()=>{active=false;};},[pack,language]);
 const dispatch=action=>{const previous=current.current;if(!previous.catalog)return;const value=reduceCompletion(previous.value,action,previous.catalog);let warning;try{warning=writeCompletion(globalThis.localStorage,value);}catch{warning=writeCompletion(null,value);}const next={...previous,value,warning};current.current=next;setState(next);};
 return {ended(receipt){if(receipt?.context)dispatch({type:'ended',sectionId:receipt.context.sectionId,requiredParts:receipt.context.requiredParts,part:receipt.part});},ready:!!state.catalog,warning:state.warning,isComplete:id=>sectionComplete(state.value,id),stepComplete:id=>stepComplete(state.value,id,state.catalog),toggle(id){const previous=current.current;if(!previous.catalog)return;const value=reduceCompletion(previous.value,{type:sectionComplete(previous.value,id)?'undo':'mark',sectionId:id},previous.catalog);let warning;try{warning=writeCompletion(globalThis.localStorage,value);}catch{warning=writeCompletion(null,value);}const next={...previous,value,warning};current.current=next;setState(next);}};
}
