import SourceIcon from './SourceIcon.jsx';
import MediaIcon from './MediaIcon.jsx';
import React from 'react';
import {GlassIconButton} from '../vendor/glass/components/glass/GlassIconButton.jsx';
import {GlassButton} from '../vendor/glass/components/glass/GlassButton.jsx';
import {Icon} from '../vendor/glass/components/icons/Icon.jsx';
const time=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export default function AudioControls({state,owner,label,onPlay,onPause,onResume,onRestart,compact=false,previous,next,onPrevious,onNext,domain,localRestart=false}){
 const mine=state.owner===owner,active=mine&&['starting','playing','paused','gap'].includes(state.status);
 if(compact)return <div className="compact-transport"><GlassIconButton size={44} label={`Previous ${domain||'source'}`} disabled={!previous} onClick={onPrevious}><span aria-hidden="true"><Icon name="chevronLeft"/></span></GlassIconButton><GlassButton className="owner-toggle" aria-description={state.fullTitle||state.title} variant="dark" onClick={active?(state.status==='paused'?onResume:onPause):onPlay} disabled={active?state.status==='starting':!onPlay} aria-label={active?`${state.status==='paused'?'Resume':'Pause'} ${label}`:label}><MediaIcon paused={active&&state.status!=='paused'}/><span>{state.title||label}</span></GlassButton><GlassIconButton size={44} label={`Next ${domain||'source'}`} disabled={!next} onClick={onNext}><span aria-hidden="true"><Icon name="chevronRight"/></span></GlassIconButton>{active&&<progress className="dock-track" aria-label={`${state.title}: ${time(state.elapsed)} of ${time(state.duration)}`} max={state.duration||1} value={state.elapsed}/>} {state.error&&<span role="status">{state.error}</span>}</div>;
 if(localRestart)return <GlassIconButton size={44} label={`Restart ${label.replace(/^Play /,'')}`} onClick={onRestart}><SourceIcon restart/></GlassIconButton>;
 return <div className={`inline-player ${compact?'compact-player':''}`} aria-label={`${label} player`}><div className="inline-player-actions"><GlassIconButton size={44} tone={active?'dark':'light'} label={active?(state.status==='paused'?`Resume ${label}`:`Pause ${label}`):label} disabled={mine&&state.status==='starting'} onClick={active?(state.status==='paused'?onResume:onPause):onPlay}><MediaIcon paused={active&&state.status!=='paused'}/></GlassIconButton><div>{active&&<strong>{state.title}</strong>}{owner==='guide'&&active&&!compact&&<small>Stops for discussion</small>}{mine&&(active||state.error)&&<span role="status">{state.error||({starting:'Loading…',playing:'Playing',paused:'Paused',idle:'Ready',error:'Playback unavailable'}[state.status])}</span>}</div>{active&&<GlassButton size="sm" onClick={onRestart} aria-label={`Restart ${label}`}>Restart</GlassButton>}</div>{active&&state.duration>0&&<div className="media-progress"><progress aria-label={`${state.title} recording progress`} max={state.duration} value={state.elapsed}/><span>{time(state.elapsed)} / {time(state.duration)}</span></div>}</div>;
}
