import React,{useState,useEffect} from 'react';
import { GlassSurface } from '../vendor/glass/components/glass/GlassSurface.jsx';
import { GlassButton } from '../vendor/glass/components/glass/GlassButton.jsx';
import InstallControls from './InstallControls.jsx';
export default function OfflineControls({state,onSave,onCancel,onRemove,onCheck,language="eng"}){const spanish=language==='spa';const [confirm,setConfirm]=useState(false);const[downloadBytes,setDownloadBytes]=useState(null);useEffect(()=>{let active=true;setDownloadBytes(null);fetch(spanish?'/offline-spa.json':'/offline-shell.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(m=>{if(active&&Array.isArray(m.entries))setDownloadBytes(m.entries.reduce((n,e)=>n+e.bytes,0));}).catch(()=>{});return()=>{active=false;};},[language]);return <><InstallControls language={language}/><GlassSurface as="details" open level={2} shadow="rest" style={{padding:'10px 14px',marginBottom:12}}><summary style={{cursor:'pointer',minHeight:24}}>Offline passage · {state.updateAvailable?'Update available':state.saved?'Saved':'Not saved'}</summary>
 <p className="eyebrow">{spanish?'Español · Marcos 1:1–13 · text and images only':'English · Mark 1:1–13'}</p>{downloadBytes!==null&&<p className="reading-note">Complete offline download: {(downloadBytes/1048576).toFixed(1)} MB ({downloadBytes.toLocaleString()} bytes).</p>}<p role="status" className="offline-status">{state.status==='checking'?'Checking saved files…':state.status==='saving'?`Verified ${(state.bytes/1048576).toFixed(1)}${state.total?` of ${(state.total/1048576).toFixed(1)}`:''} MB…`:state.updateAvailable?(spanish?'An older verified Spanish pack is saved. Save this version for its text and images; narration is unavailable.':'An older verified passage is saved. Save this version for its complete offline recordings.'):state.saved?'Saved on this device · files verified':'Not saved on this device'}</p>
 {state.error&&<p role="alert">{state.error}{(state.saved||state.previousSaved)?' The previous verified pack is still available.':''}</p>}
 <div className="offline-actions">{state.status==='saving'?<GlassButton onClick={onCancel}>Cancel save</GlassButton>:<><GlassButton onClick={onSave} disabled={state.status==='checking'}>{state.saved?'Verify and save again':'Save for offline'}</GlassButton>{(state.saved||state.previousSaved||state.corrupt)&&<><GlassButton onClick={onCheck}>Check saved files</GlassButton><GlassButton onClick={()=>setConfirm(true)}>Remove saved passage</GlassButton></>}</>}{confirm&&<><span>Remove this passage’s saved content?</span><GlassButton onClick={()=>{setConfirm(false);onRemove();}}>Confirm removal</GlassButton><GlassButton onClick={()=>setConfirm(false)}>Keep saved passage</GlassButton></>}</div>
 <p className="reading-note">{spanish?'Saves the app, Spanish guide, both Scripture editions, terms, supplements, and five image/map files. Narration is unavailable. Map labels remain English. Optional network fonts are not saved.':'Saves the app, guide, Scripture, terms, eight images and prepared ElevenLabs recordings. Online video links and optional network fonts are not saved. The optional browser voice fallback depends on your device.'}</p>
 </GlassSurface></>;}
