import {storedNarrationPreference} from '../lib/narration.js';
import NarrationPreference from './NarrationPreference.jsx';
import {storedMediaQuality} from '../lib/media-variants.js';
import React,{useState,useEffect} from 'react';
import { GlassSurface } from '../vendor/glass/components/glass/GlassSurface.jsx';
import { GlassButton } from '../vendor/glass/components/glass/GlassButton.jsx';
import MediaQuality from './MediaQuality.jsx';
import InstallControls from './InstallControls.jsx';
export default function OfflineControls({state,onSave,onCancel,onRemove,onCheck,language="eng",audioComplete=false,pendingEditionTitles=[]}){const [narration,setNarration]=useState(()=>storedNarrationPreference());useEffect(()=>{const changed=()=>{setNarration(storedNarrationPreference());onCheck?.();};window.addEventListener('fia-narration',changed);return()=>window.removeEventListener('fia-narration',changed);},[onCheck]);const [quality,setQuality]=useState(()=>storedMediaQuality());useEffect(()=>{const changed=()=>setQuality(storedMediaQuality());window.addEventListener('fia-media-quality',changed);return()=>window.removeEventListener('fia-media-quality',changed);},[]);const spanish=language==='spa';const pending=pendingEditionTitles.length>0;const [confirm,setConfirm]=useState(false);const[totals,setTotals]=useState(null);useEffect(()=>{let active=true;setTotals(null);const base=spanish?'/offline-spa':'/offline-shell';Promise.all(['','-medium'].map(suffix=>fetch(base+suffix+(narration==='ai-only'?'':'-'+narration)+'.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(m=>[...new Map(m.entries.map(e=>[e.path,e])).values()].reduce((n,e)=>n+e.bytes,0)))).then(([original,medium])=>{if(active)setTotals({original,medium});}).catch(()=>{});return()=>{active=false;};},[language,narration]);const downloadBytes=totals?.[quality]??null;return <><NarrationPreference/><MediaQuality/>{totals&&<p className="reading-note">Medium {(totals.medium/1_000_000).toFixed(1)} MB · Original {(totals.original/1_000_000).toFixed(1)} MB · saves {((totals.original-totals.medium)/1_000_000).toFixed(1)} MB ({(100*(totals.original-totals.medium)/totals.original).toFixed(0)}%).</p>}<InstallControls language={language}/>{pending&&<p>Audio pending: {pendingEditionTitles.join(', ')}.</p>}<GlassSurface as="details" open level={2} shadow="rest" style={{padding:'10px 14px',marginBottom:12}}><summary style={{cursor:'pointer',minHeight:24}}>Offline passage · {state.updateAvailable?'Update available':state.saved?'Saved':'Not saved'}</summary>
 <p className="eyebrow">{spanish?(audioComplete?(pending?'Español · Marcos 1:1–13 · text, images and available narration':'Español · Marcos 1:1–13 · text, images and narration'):'Español · Marcos 1:1–13 · text and images only'):'English · Mark 1:1–13'}</p>{downloadBytes!==null&&<p className="reading-note">{quality==='medium'?'Medium':'Original'} offline download: {(downloadBytes/1_000_000).toFixed(1)} MB ({downloadBytes.toLocaleString()} bytes).</p>}<p role="status" className="offline-status">{state.status==='checking'?'Checking saved files…':state.status==='saving'?`Verified ${(state.bytes/1_000_000).toFixed(1)}${state.total?` of ${(state.total/1_000_000).toFixed(1)}`:''} MB…`:state.updateAvailable?'A verified pack is saved. Save again for the current narration preference and app version.':state.saved?`${state.quality==='medium'?'Medium':'Original'} saved on this device · files verified`:'Not saved on this device'}</p>
 {state.error&&<p role="alert">{state.error}{(state.saved||state.previousSaved)?' The previous verified pack is still available.':''}</p>}
 <div className="offline-actions">{state.status==='saving'?<GlassButton onClick={onCancel}>Cancel save</GlassButton>:<><GlassButton onClick={onSave} disabled={state.status==='checking'}>{state.saved?'Verify and save again':'Save for offline'}</GlassButton>{(state.saved||state.previousSaved||state.corrupt)&&<><GlassButton onClick={onCheck}>Check saved files</GlassButton><GlassButton onClick={()=>setConfirm(true)}>Remove saved passage</GlassButton></>}</>}{confirm&&<><span>Remove this passage’s saved content?</span><GlassButton onClick={()=>{setConfirm(false);onRemove();}}>Confirm removal</GlassButton><GlassButton onClick={()=>setConfirm(false)}>Keep saved passage</GlassButton></>}</div>
 <p className="reading-note">Saves the app, text, images and recordings selected by your narration preference. Aquifer only saves available Aquifer recordings; unmatched audio is unavailable. Other recording alternatives, online videos and optional network fonts are not downloaded.</p>
 </GlassSurface></>;}
