import React,{useState} from 'react';
import { GlassSurface } from '../vendor/glass/components/glass/GlassSurface.jsx';
import { GlassButton } from '../vendor/glass/components/glass/GlassButton.jsx';
export default function OfflineControls({state,onSave,onCancel,onRemove,onCheck}){const [confirm,setConfirm]=useState(false);return <GlassSurface as="details" level={2} shadow="rest" style={{padding:'10px 14px',marginBottom:12}}><summary style={{cursor:'pointer',minHeight:24}}>Offline passage · {state.updateAvailable?'Update available':state.saved?'Saved':'Not saved'}</summary>
 <p className="eyebrow">Save this passage</p><p role="status" className="offline-status">{state.status==='checking'?'Checking saved files…':state.status==='saving'?`Verified ${(state.bytes/1048576).toFixed(1)}${state.total?` of ${(state.total/1048576).toFixed(1)}`:''} MB…`:state.updateAvailable?'An older verified passage is saved. Save this version for its complete offline recordings.':state.saved?'Saved on this device · files verified':'Not saved on this device'}</p>
 {state.error&&<p role="alert">{state.error}{(state.saved||state.previousSaved)?' The previous verified pack is still available.':''}</p>}
 <div className="offline-actions">{state.status==='saving'?<GlassButton onClick={onCancel}>Cancel save</GlassButton>:<><GlassButton onClick={onSave} disabled={state.status==='checking'}>{state.saved?'Verify and save again':'Save for offline'}</GlassButton>{(state.saved||state.previousSaved||state.corrupt)&&<><GlassButton onClick={onCheck}>Check saved files</GlassButton><GlassButton onClick={()=>setConfirm(true)}>Remove saved passage</GlassButton></>}</>}{confirm&&<><span>Remove this passage’s saved content?</span><GlassButton onClick={()=>{setConfirm(false);onRemove();}}>Confirm removal</GlassButton><GlassButton onClick={()=>setConfirm(false)}>Keep saved passage</GlassButton></>}</div>
 <p className="reading-note">Saves the app, guide, Scripture, terms, eight images and prepared ElevenLabs recordings. Online video links and optional network fonts are not saved. The optional browser voice fallback depends on your device.</p>
 </GlassSurface>;}
