import alignmentIndex from '../data/english-alignment.json';
import {validAlignment,alignmentPosition} from '../lib/english-alignment.js';
import AlignedVerse from './AlignedVerse.jsx';
import SourceHighlight from './SourceHighlight.jsx';
import SourceIcon from './SourceIcon.jsx';
import {GlassIconButton}from'../vendor/glass/components/glass/GlassIconButton.jsx';
import VersionSegments from './VersionSegments.jsx';
import React from 'react';
import { GlassSelect } from '../vendor/glass/components/forms/GlassSelect.jsx';
import { ScripturePassage } from '../vendor/glass/components/scripture/ScripturePassage.jsx';
import SourceDetails from './SourceDetails.jsx';
export const VERSION_LABELS={BereanStandardBible:'Berean Standard Bible (BSB)',unfoldingWordLiteral:'unfoldingWord Literal Text (ULT)',unfoldingWordSimplified:'unfoldingWord Simplified Text (UST)'};
export function VersionPicker({value,onChange}){return <GlassSelect label="Scripture version" aria-label="Scripture version" value={value} onChange={onChange} options={Object.entries(VERSION_LABELS).map(([value,label])=>({value,label}))} style={{marginBottom:18}}/>;}
export default function ScripturePanel({bible,onVersion,player,transport,onSource,versions,reference="Mark 1:1–13",lang="en",verseAdapter,sourceContent,playback}){const [loaded,setLoaded]=React.useState(null);const descriptor=verseAdapter?null:alignmentIndex.find(d=>d.id===`scripture-${bible.resourceCode}`);React.useEffect(()=>{setLoaded(null);if(!descriptor)return;const abort=new AbortController();(async()=>{try{const response=await fetch(descriptor.path,{signal:abort.signal});if(!response.ok)throw Error('Unavailable alignment');const bytes=await response.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(bytes.byteLength!==descriptor.bytes||digest!==descriptor.sha256)throw Error('Stale alignment');const data=JSON.parse(new TextDecoder().decode(bytes));if(validAlignment(data,descriptor,bible)&&!abort.signal.aborted)setLoaded(data);}catch{/* Optional timing data never blocks the verified recording. */}})();return()=>abort.abort();},[descriptor,bible]);const alignment=descriptor&&loaded?.id===descriptor.id&&validAlignment(loaded,descriptor,bible)?loaded:null;const position=alignment?alignmentPosition(alignment,playback):null;return <section aria-label="Reference Scripture"><VersionSegments value={bible.resourceCode} onChange={onVersion} options={versions}/><SourceHighlight as={ScripturePassage} state={verseAdapter||alignment?null:playback} domain="scripture" sourceIds={[`scripture-${bible.resourceCode}`]} label="Whole Scripture passage recording" key={bible.resourceCode} footer={transport} headerAction={<div className="card-players"><GlassIconButton size={44} label="Scripture source and attribution" onClick={onSource}><SourceIcon size={18}/></GlassIconButton>{player}</div>} className="scripture-text" reference={reference} version={versions?.find(v=>v.value===bible.resourceCode)?.label??(bible.resourceCode==='BereanStandardBible'?'BSB':bible.resourceCode==='unfoldingWordLiteral'?'ULT':'UST')} source={sourceContent??<SourceDetails item={bible}/>} script="latin" lang={lang} verses={verseAdapter?verseAdapter(bible.verses).map((v,i)=>({...v,text:<SourceHighlight state={playback} domain="scripture" sourceIds={[`spa-${bible.id}-${bible.verses[i].id}`]} label={`Verse ${v.n}`}>{v.text}</SourceHighlight>})):bible.verses.map((v,i)=>({n:v.verse,text:alignment?<AlignedVerse verse={alignment.verses[i]} position={position}/>:v.text}))}/></section>;}
