import useGuideCompletion from '../hooks/useGuideCompletion.js';
import FloatingDock from './FloatingDock.jsx';
import SourceHighlight from './SourceHighlight.jsx';
import AudioDisclosureInfo from './AudioDisclosureInfo.jsx';
import ScripturePanel from './ScripturePanel.jsx';
import {spanishScriptureVerses} from '../lib/scripture-view.js';
import GuideScreen from './GuideScreen.jsx';
import {spanishGuideInteraction,spanishGuideCompletion,spanishGuideView,guideBodyHtml} from '../lib/guide-presentation.js';
import ResourceScreen from './ResourceScreen.jsx';
import ResourceTile from './ResourceTile.jsx';
import {titleOnlySupplement} from '../lib/resource-presentation.js';
import VersionSegments from './VersionSegments.jsx';
import {spanishPendingNotices,spanishOwnerIds} from '../lib/spanish-audio.js';
import useSpanishAudio from '../hooks/useSpanishAudio.js';
import {storedTheme,saveSharedTheme} from '../lib/workspace.js';
import SourceIcon from './SourceIcon.jsx';
import AudioControls from './AudioControls.jsx';
import SharedTransport from './SharedTransport.jsx';
import{GlassSelect}from'../vendor/glass/components/forms/GlassSelect.jsx';
import{CatalogRow}from'../vendor/glass/components/resources/CatalogRow.jsx';
import React,{useEffect,useState,useRef}from'react';
import{AuroraField}from'../vendor/glass/components/glass/AuroraField.jsx';
import{GlassSurface}from'../vendor/glass/components/glass/GlassSurface.jsx';
import{GlassButton}from'../vendor/glass/components/glass/GlassButton.jsx';
import{ResourceCard}from'../vendor/glass/components/resources/ResourceCard.jsx';
import{GlassSearch}from'../vendor/glass/components/forms/GlassSearch.jsx';
import{GlassIconButton}from'../vendor/glass/components/glass/GlassIconButton.jsx';
import{Icon}from'../vendor/glass/components/icons/Icon.jsx';
import{OfflineController}from'../lib/offline.js';
import{browserStorage}from'../lib/session.js';
import{restoreSpanish,saveSpanish,spanishAsset}from'../lib/language-pack.js';
import{SafeHtml}from'./SourceDetails.jsx';
import ResourceDialog from'./ResourceDialog.jsx';
import PassageTabs from'./PassageTabs.jsx';
import SessionHeader from'./SessionHeader.jsx';
import LanguagesPanel from'./LanguagesPanel.jsx';
import OfflineControls from'./OfflineControls.jsx';
function Rights({rights}){return <><p>{rights.licenseInfo?.copyright?.holder?.name} {rights.licenseInfo?.copyright?.dates}</p>{rights.licenseInfo?.licenses?.map((l,i)=><p key={i}><a href={l.eng.url}>{l.eng.name}</a></p>)}<SafeHtml html={rights.adaptationNotice??rights.sourceAdaptationNoticeHtml??''}/>{rights.outputLicense&&<p><a href={rights.outputLicense.url}>{rights.outputLicense.name}</a></p>}{rights.attributionDiscrepancy&&<p>{rights.attributionDiscrepancy}</p>}</>;}
export default function SpanishSession({pack:sourcePack,onLanguage,busy,error,entryView,onClearLanguageError}){
 const pack=React.useMemo(()=>spanishGuideView(sourcePack),[sourcePack]);const completion=useGuideCompletion(pack,'spa');
 const[boot]=useState(()=>restoreSpanish(browserStorage(),pack));const[state,setState]=useState(()=>{const{notice,...seed}=boot;return {...seed,view:entryView??seed.view};});const[notice]=useState(boot.notice??'');const[themeNotice,setThemeNotice]=useState('');const[storageNotice,setStorageNotice]=useState('');const[theme,setTheme]=useState(()=>storedTheme(browserStorage()));const[selection,setSelection]=useState(null);const[offlineState,setOfflineState]=useState({status:'checking',saved:false});const offline=useRef(null);
 useEffect(()=>{document.documentElement.dataset.theme=theme;setThemeNotice(saveSharedTheme(browserStorage(),theme)?'':'Theme cannot be stored on this device.');},[theme]);useEffect(()=>{setStorageNotice(saveSpanish(browserStorage(),state)?'':'Spanish progress cannot be stored on this device. You can continue.');},[state]);
 useEffect(()=>{const c=new OfflineController(setOfflineState,'spa');offline.current=c;c.init();return()=>c.dispose();},[]);
 const lastContent=useRef(entryView??(boot.view==='languages'?'guide':boot.view));
 const update=delta=>setState(s=>({...s,...delta}));const groups=pack.guide.groups.filter(g=>g.ordinaryQueue),index=groups.findIndex(g=>g.id===state.groupId),group=groups[index];const sectionGroups=groups.filter(g=>g.section===group.section),sectionIndex=sectionGroups.findIndex(g=>g.id===group.id);const sectionTitles=pack.guide.blocks.filter(b=>b.element==='h2');const scroll=useRef(null);useEffect(()=>{if(scroll.current)scroll.current.scrollTop=0;},[state.groupId]);const allResources=[...pack.terms,...pack.media];const resources=pack.resourceOrder?pack.resourceOrder.map(id=>allResources.find(r=>r.id===id)).filter(Boolean):allResources;const resourceFilter=state.resourceFilter??'all';const visible=resources.filter(r=>(resourceFilter==='all'||r.kind===resourceFilter)&&r.title.toLowerCase().includes(state.query.toLowerCase()));
 const playback=useSpanishAudio(pack);
 const descriptor=(domain,id,title,anchor=null)=>({domain,id,title,anchor});
 const guideSelection=descriptor('guide',group.id,`${sectionTitles.find(b=>b.section===group.section)?.text??''}`);
 const bible=pack.scripture.find(b=>b.id===state.version);
 const scriptureSelection=descriptor('scripture',bible.id,bible.title);
 const resourceSelection=(item,anchor=null)=>descriptor('resources',item.id,item.title,anchor);
 const moveGuide=id=>{playback.stop();const section=groups.find(g=>g.id===id).section;update({groupId:id,visitedSections:[...new Set([...(state.visitedSections??[group.section]),section])],finished:false});};
 const playResource=(item,anchor=null)=>{update({resourceId:item.id});playback.start(resourceSelection(item,anchor));};
 const selectedResource=visible.find(r=>r.id===(playback.selection?.domain==='resources'?playback.selection.id:state.resourceId))??visible[0];
 const activeGuide=(playback.selection?.domain==='guide'&&playback.selection.id===group.id)||playback.selection?.anchor===group.id;
 const nestedIds=pack.derivedAssociations.filter(a=>a.scope==='activity'&&group.blockIds.some(id=>+id.match(/u(\d+)$/)[1]===a.cueNumber)).flatMap(a=>a.resourceIds);
 const nestedResource=resources.find(r=>r.id===state.resourceId&&nestedIds.includes(r.id))??resources.find(r=>nestedIds.includes(r.id));
 const hasScripture=group.blockIds.some(id=>pack.guide.blocks.find(b=>b.id===id)?.action==='manual-source-read; audio-blocked');
 const nestedReady=playback.completed&&playback.selection?.domain==='guide'&&playback.selection.id===group.id&&(hasScripture||nestedResource);
 const nestedSelection=hasScripture?{...scriptureSelection,anchor:group.id}:nestedResource?resourceSelection(nestedResource,group.id):null;
 const transport=(mode='guide')=>{const anchored=mode==='guide'&&activeGuide;const current=mode==='guide'?(nestedReady?nestedSelection:guideSelection):mode==='scripture'?scriptureSelection:selectedResource?resourceSelection(selectedResource):null;const controlsSelection=(anchored||mode==='resources'&&playback.selection||mode==='scripture'&&playback.selection?.domain==='scripture')?playback.selection:current;const mine=controlsSelection&&playback.selection?.id===controlsSelection.id&&playback.selection?.domain===controlsSelection.domain;const active=mine&&['starting','playing','paused','gap','restoring'].includes(playback.state.status);const resourceIndex=visible.findIndex(r=>r.id===(controlsSelection?.id??selectedResource?.id));const previous=mode==='guide'?groups[index-1]:mode==='resources'?visible[resourceIndex-1]:null;const next=mode==='guide'?groups[index+1]:mode==='resources'?visible[resourceIndex+1]:null;const play=()=>playback.start(nestedReady&&mode==='guide'?nestedSelection:mine&&playback.completed?playback.selection:current);return <SharedTransport><AudioControls compact owner={mine?playback.state.owner:mode==='guide'?'guide':mode==='scripture'?'scripture':'resources'} state={nestedReady&&mode==='guide'?{status:'idle',title:nestedSelection.title}:mine?playback.state:{status:'idle',title:current?.title??'Narration unavailable'}} label={`Play ${(mine&&!nestedReady?playback.selection?.title:current?.title)??'Spanish narration'}`} onPlay={current&&playback.available(current)?play:undefined} onPause={playback.pause} onResume={playback.resume} onRestart={playback.restart} previous={previous} next={next} domain={mode==='guide'?'guide activity':mode==='resources'?'resource':'Scripture'} onPrevious={()=>mode==='guide'?moveGuide(previous.id):playResource(previous)} onNext={()=>mode==='guide'?moveGuide(next.id):playResource(next)} nextPrimary={mine&&playback.completed&&!nestedReady&&!!next}/></SharedTransport>;};
 const localPlayer=item=><AudioControls owner="resources" state={{status:'idle',owner:playback.state.owner}} localRestart={playback.selection?.id===item.id&&['starting','playing','paused','gap','restoring'].includes(playback.state.status)} label={`Play ${item.title}`} onPlay={playback.available(resourceSelection(item))?()=>playResource(item,state.view==='guide'?group.id:null):undefined} onPause={playback.pause} onResume={playback.resume} onRestart={playback.restart}/>;
 const supplements=id=>pack.supplements.filter(s=>s.targetId===id);
 const present=item=>{const extra=supplements(item.id);return {...item,playbackSourceIds:spanishOwnerIds(pack,resourceSelection(item)).slice(0,1),assetPath:item.assetPath?spanishAsset(item.assetPath):undefined,content:item.originalHtml,mediaUrl:item.mediaUrl??item.originalHtml?.match(/href=['"]([^'"]+)/)?.[1],displayMeta:item.pixelsLanguage==='eng'||item.origin?.includes('AI')?'AI translated':'',notice:item.pixelsLanguage==='eng'?'Map labels remain English; the title is AI translated.':item.notice,attributions:[item,...extra.map(s=>({source:{url:s.rights.sourceUrl??item.source?.url},rights:s.rights}))],supplementContent:<>{item.visualNarration&&<section aria-label="Spanish visual description"><p>{item.visualNarration.label}</p><SourceHighlight as="div" state={playback.state} domain="resources" sourceIds={spanishOwnerIds(pack,resourceSelection(item)).slice(0,1)} label="Visual description"><p>{item.visualNarration.text}</p></SourceHighlight></section>}{extra.filter(s=>!titleOnlySupplement(item,s)).map(s=><section key={s.id}><SafeHtml html={s.content}/></section>)}</>};};
 const detail=selected=>{const item=resources.find(r=>r.id===selected.id)??selected;update({resourceId:item.id});setSelection({resourceId:item.id,title:item.title,item:present(item)});};
 const sourceBlocks=(ids,domain='guide')=><div lang="es">{ids.map(id=><SourceHighlight as="div" key={id} state={playback.state} domain={domain} sourceIds={[`spa-${id}`]} label="Guide source block"><SafeHtml html={guideBodyHtml(pack.guide.blocks.find(b=>b.id===id))}/></SourceHighlight>)}</div>;
 const card=item=><ResourceTile key={item.id} item={present(item)} onOpen={()=>detail(item)} player={localPlayer(item)} audioAvailable={playback.available(resourceSelection(item))}/>;
 const info=<GlassIconButton size={44} label="Spanish source and attribution" onClick={()=>setSelection({title:'Spanish source and attribution',children:<><AudioDisclosureInfo warning={playback.disclosureWarning} onReplay={playback.replayIntroduction}/><Rights rights={pack.guide.rights}/>{sourceBlocks(pack.guide.blocks.filter(b=>b.visibility==='source-metadata').map(b=>b.id))}<p>{playback.hasRecordings?'Prepared Spanish recordings are available. Written source and translation notices remain below.':'No Spanish narration is available. Source text and AI supplements do not establish heard quality.'}</p></>})}><SourceIcon size={18}/></GlassIconButton>;
 return <AuroraField className="app-aurora" drift={false}><div className={`app-shell ${state.view==='resources'?'resources-view':''}`} data-content-language="spa"><div className="app-content" inert={selection?true:undefined}><SessionHeader theme={theme} onThemeChange={setTheme} visited={0} offlineState={offlineState} onSettings={()=>setSelection({settings:true})}/><main id="session-main" tabIndex="-1">{notice&&<p role="status">{notice}</p>}{playback.storageWarning&&<p role="status">{playback.storageWarning}</p>}{themeNotice&&<p role="status">{themeNotice}</p>}{storageNotice&&<p role="status">{storageNotice}</p>}{error&&state.view!=='languages'&&<p role="alert">{error}</p>}
 {state.view==='languages'&&<LanguagesPanel preparedAudio={pack.preparedAudio??null} value="spa" onChange={code=>{if(code==='spa'){onClearLanguageError();update({view:lastContent.current});}else {playback.suspend();onLanguage(code,lastContent.current);}}} busy={busy} error={error}/>}
 {state.view==='guide'&&<section id="panel-guide" role="tabpanel" aria-labelledby="tab-guide"><GuideScreen completion={completion} model={{stepId:String(group.section),steps:sectionTitles.map(b=>({value:String(b.section),label:`${b.section}/6 · ${b.text}`})),index:sectionIndex,total:sectionGroups.length,unitId:group.id,language:'es',body:sourceBlocks(group.blockIds),interactionKind:spanishGuideInteraction(group,pack.guide.blocks),...spanishGuideCompletion(group,groups,state.visitedSections??[group.section]),finished:state.finished}} onStep={section=>moveGuide(groups.find(g=>g.section===Number(section)).id)} onIndex={()=>setSelection({title:sectionTitles.find(b=>b.section===group.section).text,children:sectionGroups.map((g,i)=><CatalogRow key={g.id} data-unit-id={g.id} aria-current={g.id===group.id?'location':undefined} subject={`${completion.isComplete(g.id)?'✓ Completed · ':''}Section ${i+1}/${sectionGroups.length}`} title={pack.guide.blocks.find(b=>b.id===g.blockIds[0]).text} onOpen={()=>{moveGuide(g.id);setSelection(null);}}/>)})} actions={<>{info}{playback.selection&&<AudioControls state={playback.state} localRestart label={playback.selection.title} onRestart={playback.restart}/>}</>} transport={transport('guide')} onFinish={()=>{if(spanishGuideCompletion(group,groups,state.visitedSections??[group.section]).canFinish)update({finished:true});}}>{hasScripture&&<div className="scripture-prompt"><GlassButton variant="dark" disabled={!playback.available(scriptureSelection)} onClick={()=>playback.start({...scriptureSelection,anchor:group.id})}>Play Scripture {bible.shortLabel??(bible.id==='ReinaValera1909'?'RV1909':'Referencia')}</GlassButton><button className="text-button" onClick={()=>setSelection({title:bible.title,children:<div lang="es">{bible.verses.map(v=><SafeHtml key={v.id} html={v.originalHtml}/>)}</div>})}>Read the selected Scripture</button></div>}<div className="context-resources">{pack.derivedAssociations.filter(a=>a.scope==='activity'&&group.blockIds.some(id=>+id.match(/u(\d+)$/)[1]===a.cueNumber)).flatMap(a=>a.resourceIds).map(id=>card(resources.find(r=>r.id===id)))}</div>{group.section===4&&group.blockIds.some(id=>/u06[56]$/.test(id))&&<GlassButton onClick={()=>setSelection({example:true,title:'Optional source example — possible responses'})}>Show source example</GlassButton>}</GuideScreen></section>}
 {state.view==='scripture'&&<section id="panel-scripture" role="tabpanel" aria-labelledby="tab-scripture"><ScripturePanel playback={playback.state} bible={{...bible,resourceCode:bible.id}} versions={pack.scripture.map(b=>({value:b.id,label:b.shortLabel??(b.id==='ReinaValera1909'?'RV1909':'Referencia')}))} reference="Marcos 1:1–13" lang="es" verseAdapter={spanishScriptureVerses} onVersion={version=>{playback.stop();update({version});}} sourceContent={<>{bible.notice&&<p>{bible.notice}</p>}{bible.attribution&&<p>{bible.attribution}</p>}<Rights rights={bible.rights}/></>} onSource={()=>setSelection({title:bible.title,children:<Rights rights={bible.rights}/>})} player={playback.available(scriptureSelection)?<AudioControls state={{status:'idle',owner:playback.state.owner}} owner="scripture" label={`Play ${bible.title}`} localRestart={playback.selection?.domain==='scripture'&&playback.selection.id===bible.id&&['playing','paused','starting','restoring','gap'].includes(playback.state.status)} onPlay={playback.available(scriptureSelection)?()=>playback.start(scriptureSelection):undefined} onRestart={playback.restart}/>:undefined} transport={transport('scripture')}/></section>}
 {state.view==='resources'&&<ResourceScreen items={visible.map(present)} query={state.query} onQuery={query=>{if(['paused','restoring'].includes(playback.state.status))playback.stop();update({query});}} filter={resourceFilter} onFilter={value=>{if(['paused','restoring'].includes(playback.state.status))playback.stop();update({resourceFilter:value});}} onOpen={detail} player={localPlayer} available={item=>playback.available(resourceSelection(item))} language="es"/>}
 </main><FloatingDock><PassageTabs value={state.view} onChange={view=>{if(view!=='languages')lastContent.current=view;update({view});}}/>{(state.view==='resources'||state.view==='languages')&&playback.hasRecordings&&<div className="playback-dock">{transport('resources')}</div>}</FloatingDock></div>{selection&&<ResourceDialog playback={playback.state} transport={playback.hasRecordings?transport(selection.resourceId?'resources':'guide'):undefined} localPlayer={selection.resourceId&&playback.available(resourceSelection(resources.find(r=>r.id===selection.resourceId)))?localPlayer(resources.find(r=>r.id===selection.resourceId)):undefined} selection={selection.example?{...selection,children:<><GlassButton disabled={!playback.available(descriptor('example',pack.guide.optionalExampleGroupIds[0],'Optional source example',group.id))} onClick={()=>playback.start(descriptor('example',pack.guide.optionalExampleGroupIds[0],'Optional source example',group.id))}>Play optional example</GlassButton>{sourceBlocks(pack.guide.blocks.filter(b=>b.visibility==='opt-in-example').map(b=>b.id),'resources')}</>}:selection.settings?{title:'Offline passage',children:<><OfflineControls information={<AudioDisclosureInfo onReplay={playback.replayIntroduction}/>} warning={playback.disclosureWarning} language="spa" pendingEditionTitles={pack.scripture.filter(e=>pack.narrationPendingEditionIds?.includes(e.id)).map(e=>e.title)} audioComplete={pack.preparedAudio?.complete===true} state={offlineState} onSave={()=>offline.current.save()} onCancel={()=>offline.current.cancel()} onCheck={()=>offline.current.check()} onRemove={()=>offline.current.remove()}/></>}:selection} onClose={()=>{if(selection.example&&playback.selection?.domain==='example')playback.stop();setSelection(null);}}/>}</div></AuroraField>;
}
