import React,{useEffect,useState,useRef}from'react';
import{AuroraField}from'../vendor/glass/components/glass/AuroraField.jsx';
import{GlassSurface}from'../vendor/glass/components/glass/GlassSurface.jsx';
import{GlassButton}from'../vendor/glass/components/glass/GlassButton.jsx';
import{ResourceCard}from'../vendor/glass/components/resources/ResourceCard.jsx';
import{GlassSearch}from'../vendor/glass/components/forms/GlassSearch.jsx';
import{GlassIconButton}from'../vendor/glass/components/glass/GlassIconButton.jsx';
import{Icon}from'../vendor/glass/components/icons/Icon.jsx';
import{OfflineController}from'../lib/offline.js';
import{browserStorage}from'../lib/session.js';
import{restoreSpanish,saveSpanish,spanishAsset}from'../lib/language-pack.js';
import{SafeHtml}from'./SourceDetails.jsx';
import ResourceDialog from'./ResourceDialog.jsx';
import PassageTabs from'./PassageTabs.jsx';
import SessionHeader from'./SessionHeader.jsx';
import LanguagesPanel from'./LanguagesPanel.jsx';
import OfflineControls from'./OfflineControls.jsx';
function Rights({rights}){return <><p>{rights.licenseInfo?.copyright?.holder?.name} {rights.licenseInfo?.copyright?.dates}</p>{rights.licenseInfo?.licenses?.map((l,i)=><p key={i}><a href={l.eng.url}>{l.eng.name}</a></p>)}<SafeHtml html={rights.adaptationNotice??rights.sourceAdaptationNoticeHtml??''}/>{rights.attributionDiscrepancy&&<p>{rights.attributionDiscrepancy}</p>}</>;}
export default function SpanishSession({pack,onLanguage,busy,error}){
 const[state,setState]=useState(()=>restoreSpanish(browserStorage(),pack));const[notice,setNotice]=useState(state.notice??'');const[theme,setTheme]=useState(document.documentElement.dataset.theme==='dark'?'dark':'light');const[selection,setSelection]=useState(null);const[offlineState,setOfflineState]=useState({status:'checking',saved:false});const offline=useRef(null);
 useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);useEffect(()=>{if(!saveSpanish(browserStorage(),state))setNotice('Spanish progress cannot be stored on this device. You can continue.');},[state]);
 useEffect(()=>{const c=new OfflineController(setOfflineState,'spa');offline.current=c;c.init();return()=>c.dispose();},[]);
 const update=delta=>setState(s=>({...s,...delta}));const groups=pack.guide.groups.filter(g=>g.ordinaryQueue),index=groups.findIndex(g=>g.id===state.groupId),group=groups[index];const resources=[...pack.terms,...pack.media];const visible=resources.filter(r=>r.title.toLowerCase().includes(state.query.toLowerCase()));
 const supplements=id=>pack.supplements.filter(s=>s.targetId===id);
 const detail=item=>{update({resourceId:item.id});setSelection({title:item.title,children:<div lang="es">{item.assetPath&&<img style={{maxWidth:'100%'}} src={spanishAsset(item.assetPath)} alt={item.title}/>}{item.kind==='term'&&<SafeHtml html={item.originalHtml}/>}{item.notice&&<p>{item.notice}</p>}<Rights rights={item.rights}/>{supplements(item.id).map(s=><section key={s.id}><p lang="en">{s.label} · {s.presentation.meta}</p><SafeHtml html={s.content}/><Rights rights={s.rights}/></section>)}</div>});};
 const sourceBlocks=ids=><div lang="es">{ids.map(id=><SafeHtml key={id} html={pack.guide.blocks.find(b=>b.id===id).html}/>)}</div>;
 const card=item=><ResourceCard key={item.id} title={item.title} type={item.kind} meta={[item.meta,...supplements(item.id).map(s=>s.presentation.meta)].filter(Boolean).join(' · ')||'Spanish source · narration unavailable'} image={item.assetPath?spanishAsset(item.assetPath):undefined} onOpen={()=>detail(item)} style={{width:'100%'}} aria-label={`Open ${item.title}`}/>;
 const info=<GlassIconButton aria-label="Spanish source and attribution" onClick={()=>setSelection({title:'Spanish source and attribution',children:<><Rights rights={pack.guide.rights}/>{sourceBlocks(pack.guide.blocks.filter(b=>b.visibility==='source-metadata').map(b=>b.id))}<p>No Spanish narration is available. Source text and AI supplements do not establish heard quality.</p></>})}><Icon name="info"/></GlassIconButton>;
 return <AuroraField className="app-aurora" drift={false}><div className="app-shell"><div className="app-content" inert={selection?true:undefined}><SessionHeader theme={theme} onThemeChange={setTheme} visited={0} offlineState={offlineState} onSettings={()=>setSelection({settings:true})}/><main id="session-main" tabIndex="-1"><p role="status">Español · text and images · narration unavailable</p>{notice&&<p role="status">{notice}</p>}{error&&state.view!=='languages'&&<p role="alert">{error}</p>}
 {state.view==='languages'&&<LanguagesPanel value="spa" onChange={onLanguage} busy={busy} error={error}/>}
 {state.view==='guide'&&<section id="panel-guide" role="tabpanel" aria-labelledby="tab-guide"><GlassSurface level={3} className="reading-card"><div className="content-heading"><h2>Guide · {index+1} of {groups.length}</h2>{info}</div>{sourceBlocks(group.blockIds)}<div className="context-resources">{pack.derivedAssociations.filter(a=>a.scope==='activity'&&group.blockIds.some(id=>+id.match(/u(\d+)$/)[1]===a.cueNumber)).flatMap(a=>a.resourceIds).map(id=>card(resources.find(r=>r.id===id)))}</div><div className="guide-actions"><GlassButton disabled={index===0} onClick={()=>update({groupId:groups[index-1].id})}>Previous</GlassButton><GlassButton disabled={index===groups.length-1} onClick={()=>update({groupId:groups[index+1].id})}>Next</GlassButton></div><GlassButton onClick={()=>setSelection({title:'Optional source example — possible responses',children:sourceBlocks(pack.guide.blocks.filter(b=>b.visibility==='opt-in-example').map(b=>b.id))})}>Show source example</GlassButton></GlassSurface></section>}
 {state.view==='scripture'&&<section id="panel-scripture" role="tabpanel" aria-labelledby="tab-scripture"><label>Spanish edition <select value={state.version} onChange={e=>update({version:e.target.value})}>{pack.scripture.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><GlassSurface className="reading-card" level={3}><div lang="es">{pack.scripture.find(b=>b.id===state.version).verses.map(v=><SafeHtml key={v.id} html={v.originalHtml}/>)}</div><Rights rights={pack.scripture.find(b=>b.id===state.version).rights}/></GlassSurface></section>}
 {state.view==='resources'&&<section id="panel-resources" role="tabpanel" aria-labelledby="tab-resources"><GlassSearch aria-label="Search resources" value={state.query} onChange={e=>update({query:e.target.value})}/><div className="resource-grid" lang="es">{visible.map(item=><div className="resource-tile" key={item.id}>{card(item)}</div>)}</div></section>}
 </main><div className="floating-dock"><PassageTabs value={state.view} onChange={view=>update({view})}/></div></div>{selection&&<ResourceDialog selection={selection.settings?{title:'Spanish text and images offline',children:<><p>Verified Spanish text and images only; narration unavailable. English saved files retained.</p><OfflineControls state={offlineState} onSave={()=>offline.current.save()} onCancel={()=>offline.current.cancel()} onCheck={()=>offline.current.check()} onRemove={()=>offline.current.remove()}/></>}:selection} onClose={()=>setSelection(null)}/>}</div></AuroraField>;
}
