import useSpanishAudio from '../hooks/useSpanishAudio.js';
import {storedTheme,saveSharedTheme} from '../lib/workspace.js';
import SourceIcon from './SourceIcon.jsx';
import AudioControls from './AudioControls.jsx';
import SharedTransport from './SharedTransport.jsx';
import{GlassSelect}from'../vendor/glass/components/forms/GlassSelect.jsx';
import{CatalogRow}from'../vendor/glass/components/resources/CatalogRow.jsx';
import React,{useEffect,useState,useRef}from'react';
import{AuroraField}from'../vendor/glass/components/glass/AuroraField.jsx';
import{GlassSurface}from'../vendor/glass/components/glass/GlassSurface.jsx';
import{GlassButton}from'../vendor/glass/components/glass/GlassButton.jsx';
import{ResourceCard}from'../vendor/glass/components/resources/ResourceCard.jsx';
import{GlassSearch}from'../vendor/glass/components/forms/GlassSearch.jsx';
import{GlassIconButton}from'../vendor/glass/components/glass/GlassIconButton.jsx';
import{Icon}from'../vendor/glass/components/icons/Icon.jsx';
import{OfflineController}from'../lib/offline.js';
import{browserStorage}from'../lib/session.js';
import{restoreSpanish,saveSpanish,spanishAsset}from'../lib/language-pack.js';
import{SafeHtml}from'./SourceDetails.jsx';
import ResourceDialog from'./ResourceDialog.jsx';
import PassageTabs from'./PassageTabs.jsx';
import SessionHeader from'./SessionHeader.jsx';
import LanguagesPanel from'./LanguagesPanel.jsx';
import OfflineControls from'./OfflineControls.jsx';
function Rights({rights}){return <><p>{rights.licenseInfo?.copyright?.holder?.name} {rights.licenseInfo?.copyright?.dates}</p>{rights.licenseInfo?.licenses?.map((l,i)=><p key={i}><a href={l.eng.url}>{l.eng.name}</a></p>)}<SafeHtml html={rights.adaptationNotice??rights.sourceAdaptationNoticeHtml??''}/>{rights.outputLicense&&<p><a href={rights.outputLicense.url}>{rights.outputLicense.name}</a></p>}{rights.attributionDiscrepancy&&<p>{rights.attributionDiscrepancy}</p>}</>;}
export default function SpanishSession({pack,onLanguage,busy,error,entryView,onClearLanguageError}){
 const[boot]=useState(()=>restoreSpanish(browserStorage(),pack));const[state,setState]=useState(()=>{const{notice,...seed}=boot;return {...seed,view:entryView??seed.view};});const[notice]=useState(boot.notice??'');const[themeNotice,setThemeNotice]=useState('');const[storageNotice,setStorageNotice]=useState('');const[theme,setTheme]=useState(()=>storedTheme(browserStorage()));const[selection,setSelection]=useState(null);const[offlineState,setOfflineState]=useState({status:'checking',saved:false});const offline=useRef(null);
 useEffect(()=>{document.documentElement.dataset.theme=theme;setThemeNotice(saveSharedTheme(browserStorage(),theme)?'':'Theme cannot be stored on this device.');},[theme]);useEffect(()=>{setStorageNotice(saveSpanish(browserStorage(),state)?'':'Spanish progress cannot be stored on this device. You can continue.');},[state]);
 useEffect(()=>{const c=new OfflineController(setOfflineState,'spa');offline.current=c;c.init();return()=>c.dispose();},[]);
 const lastContent=useRef(entryView??(boot.view==='languages'?'guide':boot.view));
 const update=delta=>setState(s=>({...s,...delta}));const groups=pack.guide.groups.filter(g=>g.ordinaryQueue),index=groups.findIndex(g=>g.id===state.groupId),group=groups[index];const sectionGroups=groups.filter(g=>g.section===group.section),sectionIndex=sectionGroups.findIndex(g=>g.id===group.id);const sectionTitles=pack.guide.blocks.filter(b=>b.element==='h2');const scroll=useRef(null);useEffect(()=>{if(scroll.current)scroll.current.scrollTop=0;},[state.groupId]);const allResources=[...pack.terms,...pack.media];const resources=pack.resourceOrder?pack.resourceOrder.map(id=>allResources.find(r=>r.id===id)).filter(Boolean):allResources;const visible=resources.filter(r=>r.title.toLowerCase().includes(state.query.toLowerCase()));
 const playback=useSpanishAudio(pack);
 const descriptor=(domain,id,title,anchor=null)=>({domain,id,title,anchor});
 const guideSelection=descriptor('guide',group.id,`Guide · ${sectionTitles.find(b=>b.section===group.section)?.text??''}`);
 const bible=pack.scripture.find(b=>b.id===state.version);
 const scriptureSelection=descriptor('scripture',bible.id,bible.title);
 const resourceSelection=(item,anchor=null)=>descriptor('resources',item.id,item.title,anchor);
 const moveGuide=id=>{playback.stop();update({groupId:id});};
 const playResource=(item,anchor=null)=>{update({resourceId:item.id});playback.start(resourceSelection(item,anchor));};
 const selectedResource=visible.find(r=>r.id===(playback.selection?.domain==='resources'?playback.selection.id:state.resourceId))??visible[0];
 const activeGuide=playback.selection?.domain==='guide'||playback.selection?.anchor===group.id;
 const nestedIds=pack.derivedAssociations.filter(a=>a.scope==='activity'&&group.blockIds.some(id=>+id.match(/u(\d+)$/)[1]===a.cueNumber)).flatMap(a=>a.resourceIds);
 const nestedResource=resources.find(r=>r.id===state.resourceId&&nestedIds.includes(r.id))??resources.find(r=>nestedIds.includes(r.id));
 const hasScripture=group.blockIds.some(id=>pack.guide.blocks.find(b=>b.id===id)?.action==='manual-source-read; audio-blocked');
 const nestedReady=playback.completed&&playback.selection?.domain==='guide'&&playback.selection.id===group.id&&(hasScripture||nestedResource);
 const nestedSelection=hasScripture?{...scriptureSelection,anchor:group.id}:nestedResource?resourceSelection(nestedResource,group.id):null;
 const transport=(mode='guide')=>{const anchored=mode==='guide'&&activeGuide;const current=mode==='guide'?(nestedReady?nestedSelection:guideSelection):mode==='scripture'?scriptureSelection:selectedResource?resourceSelection(selectedResource):null;const controlsSelection=(anchored||mode==='resources'&&playback.selection||mode==='scripture'&&playback.selection?.domain==='scripture')?playback.selection:current;const mine=controlsSelection&&playback.selection?.id===controlsSelection.id&&playback.selection?.domain===controlsSelection.domain;const active=mine&&['starting','playing','paused','gap','restoring'].includes(playback.state.status);const resourceIndex=visible.findIndex(r=>r.id===(controlsSelection?.id??selectedResource?.id));const previous=mode==='guide'?groups[index-1]:mode==='resources'?visible[resourceIndex-1]:null;const next=mode==='guide'?groups[index+1]:mode==='resources'?visible[resourceIndex+1]:null;const play=()=>playback.start(nestedReady&&mode==='guide'?nestedSelection:mine&&playback.completed?playback.selection:current);return <SharedTransport><AudioControls compact owner={mine?playback.state.owner:mode==='guide'?'guide':mode==='scripture'?'scripture':'resources'} state={nestedReady&&mode==='guide'?{status:'idle',title:nestedSelection.title}:mine?playback.state:{status:'idle',title:current?.title??'Narration unavailable'}} label={`Play ${(mine&&!nestedReady?playback.selection?.title:current?.title)??'Spanish narration'}`} onPlay={current&&playback.available(current)?play:undefined} onPause={playback.pause} onResume={playback.resume} onRestart={playback.restart} previous={previous} next={next} domain={mode==='guide'?'guide activity':mode==='resources'?'resource':'Scripture'} onPrevious={()=>mode==='guide'?moveGuide(previous.id):playResource(previous)} onNext={()=>mode==='guide'?moveGuide(next.id):playResource(next)} nextPrimary={mine&&playback.completed&&!nestedReady&&!!next}/></SharedTransport>;};
 const localPlayer=item=><AudioControls owner="resources" state={playback.selection?.id===item.id?playback.state:{status:'idle'}} label={`Play ${item.title}`} onPlay={playback.available(resourceSelection(item))?()=>playResource(item,state.view==='guide'?group.id:null):undefined} onPause={playback.pause} onResume={playback.resume} onRestart={playback.restart}/>;
 const supplements=id=>pack.supplements.filter(s=>s.targetId===id);
 const detail=item=>{update({resourceId:item.id});setSelection({resourceId:item.id,title:item.title,children:<div lang="es">{item.assetPath&&<img style={{maxWidth:'100%'}} src={spanishAsset(item.assetPath)} alt={item.title}/>}{(item.kind==='term'||item.kind==='video')&&<SafeHtml html={item.originalHtml}/>}<p>{item.origin}</p>{item.notice&&<p>{item.notice}</p>}<Rights rights={item.rights}/>{supplements(item.id).map(s=><section key={s.id}><p lang="en">{s.label} · {s.presentation.meta}</p><SafeHtml html={s.content}/><GlassButton disabled={!playback.available(descriptor('supplement',s.id,s.presentation?.notice??s.id))} onClick={()=>playback.start(descriptor('supplement',s.id,s.presentation?.notice??s.id,state.view==='guide'?group.id:null))}>Play supplement</GlassButton><Rights rights={s.rights}/></section>)}</div>});};
 const sourceBlocks=ids=><div lang="es">{ids.map(id=><SafeHtml key={id} html={pack.guide.blocks.find(b=>b.id===id).html}/>)}</div>;
 const card=item=><ResourceCard key={item.id} title={item.title} type={item.kind} meta={[item.meta,...supplements(item.id).map(s=>s.presentation.meta)].filter(Boolean).join(' · ')||'Spanish source · narration unavailable'} image={item.assetPath?spanishAsset(item.assetPath):undefined} onOpen={()=>detail(item)} actions={playback.available(resourceSelection(item))?localPlayer(item):undefined} style={{width:'100%'}} aria-label={`Open ${item.title}`}/>;
 const info=<GlassIconButton size={44} label="Spanish source and attribution" onClick={()=>setSelection({title:'Spanish source and attribution',children:<><Rights rights={pack.guide.rights}/>{sourceBlocks(pack.guide.blocks.filter(b=>b.visibility==='source-metadata').map(b=>b.id))}<p>{playback.hasRecordings?'Prepared Spanish recordings are available. Written source and translation notices remain below.':'No Spanish narration is available. Source text and AI supplements do not establish heard quality.'}</p></>})}><SourceIcon size={18}/></GlassIconButton>;
 return <AuroraField className="app-aurora" drift={false}><div className="app-shell"><div className="app-content" inert={selection?true:undefined}><SessionHeader theme={theme} onThemeChange={setTheme} visited={0} offlineState={offlineState} onSettings={()=>setSelection({settings:true})}/><main id="session-main" tabIndex="-1"><p role="status">{playback.hasRecordings?'Español · prepared narration':'Español · text and images · narration unavailable'}</p>{notice&&<p role="status">{notice}</p>}{playback.storageWarning&&<p role="status">{playback.storageWarning}</p>}{themeNotice&&<p role="status">{themeNotice}</p>}{storageNotice&&<p role="status">{storageNotice}</p>}{error&&state.view!=='languages'&&<p role="alert">{error}</p>}
 {state.view==='languages'&&<LanguagesPanel value="spa" onChange={code=>{if(code==='spa'){onClearLanguageError();update({view:lastContent.current});}else {playback.suspend();onLanguage(code,lastContent.current);}}} busy={busy} error={error}/>}
 {state.view==='guide'&&<section id="panel-guide" role="tabpanel" aria-labelledby="tab-guide"><div className="secondary-band guide-chooser"><GlassSelect label="Guide step" aria-label="Guide step" value={String(group.section)} options={sectionTitles.map(b=>({value:String(b.section),label:`${b.section}/6 · ${b.text}`}))} onChange={section=>moveGuide(groups.find(g=>g.section===Number(section)).id)}/><GlassButton onClick={()=>setSelection({title:sectionTitles.find(b=>b.section===group.section).text,children:sectionGroups.map((g,i)=><CatalogRow key={g.id} subject={`Section ${i+1}/${sectionGroups.length}`} title={pack.guide.blocks.find(b=>b.id===g.blockIds[0]).text} onOpen={()=>{moveGuide(g.id);setSelection(null);}}/>)})}>Section {sectionIndex+1}/{sectionGroups.length}</GlassButton></div><GlassSurface level={4} className="reading-card guide-card"><div className="content-heading"><span className="eyebrow">Guide</span>{info}{playback.selection&&<AudioControls state={playback.state} localRestart label={playback.selection.title} onRestart={playback.restart}/>}</div><div className="source-scroll" ref={scroll}>{sourceBlocks(group.blockIds)}<div className="context-resources">{pack.derivedAssociations.filter(a=>a.scope==='activity'&&group.blockIds.some(id=>+id.match(/u(\d+)$/)[1]===a.cueNumber)).flatMap(a=>a.resourceIds).map(id=>card(resources.find(r=>r.id===id)))}</div>{group.section===4&&group.blockIds.some(id=>/u06[56]$/.test(id))&&<GlassButton onClick={()=>setSelection({example:true,title:'Optional source example — possible responses',children:<><GlassButton disabled={!playback.available(descriptor('example',pack.guide.optionalExampleGroupIds[0],'Optional source example',group.id))} onClick={()=>playback.start(descriptor('example',pack.guide.optionalExampleGroupIds[0],'Optional source example',group.id))}>Play optional example</GlassButton>{sourceBlocks(pack.guide.blocks.filter(b=>b.visibility==='opt-in-example').map(b=>b.id))}</>})}>Show source example</GlassButton>}</div><div className="card-transport-footer">{transport('guide')}</div></GlassSurface></section>}
 {state.view==='scripture'&&<section id="panel-scripture" role="tabpanel" aria-labelledby="tab-scripture"><label>Spanish edition <select value={state.version} onChange={e=>{playback.stop();update({version:e.target.value});}}>{pack.scripture.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><GlassSurface className="reading-card scripture-text" level={3}><div className="source-scroll" lang="es">{pack.scripture.find(b=>b.id===state.version).verses.map(v=><SafeHtml key={v.id} html={v.originalHtml}/>)}</div>{pack.scripture.find(b=>b.id===state.version).notice&&<p>{pack.scripture.find(b=>b.id===state.version).notice}</p>}{pack.scripture.find(b=>b.id===state.version).attribution&&<p>{pack.scripture.find(b=>b.id===state.version).attribution}</p>}<Rights rights={pack.scripture.find(b=>b.id===state.version).rights}/><div className="card-transport-footer">{transport('scripture')}</div></GlassSurface></section>}
 {state.view==='resources'&&<section id="panel-resources" role="tabpanel" aria-labelledby="tab-resources"><GlassSearch aria-label="Search resources" value={state.query} onChange={e=>{playback.stop();update({query:e.target.value});}}/><div className="resource-grid" lang="es">{visible.map(item=><div className="resource-tile" key={item.id}>{card(item)}</div>)}</div></section>}
 </main>{(state.view==='resources'||state.view==='languages')&&playback.hasRecordings&&<div className="playback-dock">{transport('resources')}</div>}<div className="floating-dock"><PassageTabs value={state.view} onChange={view=>{if(view!=='languages')lastContent.current=view;update({view});}}/></div></div>{selection&&<ResourceDialog transport={playback.hasRecordings?transport(selection.resourceId?'resources':'guide'):undefined} localPlayer={selection.resourceId&&playback.available(resourceSelection(resources.find(r=>r.id===selection.resourceId)))?localPlayer(resources.find(r=>r.id===selection.resourceId)):undefined} selection={selection.settings?{title:'Spanish text and images offline',children:<><p>Verified Spanish text and images only; narration unavailable. English saved files retained.</p><OfflineControls language="spa" state={offlineState} onSave={()=>offline.current.save()} onCancel={()=>offline.current.cancel()} onCheck={()=>offline.current.check()} onRemove={()=>offline.current.remove()}/></>}:selection} onClose={()=>{if(selection.example&&playback.selection?.domain==='example')playback.stop();setSelection(null);}}/>}</div></AuroraField>;
}
