import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';
const root=path.resolve('dist'),evidence='evidence/pwa',profile=fs.mkdtempSync(path.join(os.tmpdir(),'fia-pwa-profile-')),port=4277,origin=`http://127.0.0.1:${port}`;
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.jpg':'image/jpeg','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{try{const name=new URL(req.url,origin).pathname;const file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep))throw Error();const bytes=fs.readFileSync(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]??'application/octet-stream','Cache-Control':'no-store'});res.end(bytes);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(port,'127.0.0.1',r));
let context;const results={physicalMobileInstall:'unverified; no physical device used',profileRestart:false};
async function settings(page){await page.getByRole('button',{name:'Offline passage and settings'}).click();}
try{context=await chromium.launchPersistentContext(profile,{headless:true,viewport:{width:390,height:844},reducedMotion:'reduce'});let page=await context.newPage();await page.addInitScript(()=>{window.__playCalls=0;const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(...args){window.__playCalls++;return play.apply(this,args);};});await page.goto(origin);await page.getByRole('button',{name:'Next guide activity',exact:true}).click();await page.getByTestId('current-unit').waitFor();const unit=await page.getByTestId('current-unit').getAttribute('data-unit-id');await page.getByRole('button',{name:'Switch to dark theme'}).click();await page.getByRole('tab',{name:'Scripture',exact:true}).click();await page.getByRole('radio',{name:'ULT',exact:true}).click();await page.getByRole('tab',{name:'Guide',exact:true}).click();await settings(page);await page.getByText('FIA on this device',{exact:true}).waitFor();await page.getByRole('button',{name:'Save for offline',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.offline-status')?.textContent.includes('Saved on this device'),null,{timeout:60000});
const active=await page.evaluate(async()=>{const c=await caches.open('fia-meta-v1');return(await c.match('/__fia_active__')).json();});assert.equal(active.entries.length,200);for(const p of ['/app.webmanifest','/icons/fia-192.png','/icons/fia-512.png','/icons/fia-maskable-512.png','/icons/apple-touch-icon.png'])assert(active.entries.some(e=>e.path===p&&e.group==='shell'));
results.savedFiles=active.entries.length;results.savedBytes=active.entries.reduce((n,e)=>n+e.bytes,0);await page.screenshot({path:evidence+'/settings-390.png'});await page.setViewportSize({width:320,height:740});await page.screenshot({path:evidence+'/settings-320.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Close resource'}).click();await context.setOffline(true);await page.close();page=await context.newPage();await page.goto(origin);assert.equal(await page.getByTestId('current-unit').getAttribute('data-unit-id'),unit);results.pageCloseReopen=true;await context.close();context=null;
context=await chromium.launchPersistentContext(profile,{headless:true,viewport:{width:390,height:844},reducedMotion:'reduce'});await context.setOffline(true);page=await context.newPage();await page.addInitScript(()=>{window.__playCalls=0;const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(...args){window.__playCalls++;return play.apply(this,args);};});await page.goto(origin);await page.getByTestId('current-unit').waitFor();assert.equal(await page.getByTestId('current-unit').getAttribute('data-unit-id'),unit);assert.equal(await page.evaluate(()=>window.__playCalls),0);results.profileRestart=true;results.noAutoplay=true;assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');const savedWorkspace=await page.evaluate(()=>JSON.parse(localStorage.getItem('fia.workspace.mark-1-1-13.v2')));assert.equal(savedWorkspace.guide.version,'unfoldingWordLiteral');results.themeAndEditionPreserved=true;
for(const target of ['Scripture','Resources','Guide']){await page.getByRole('tab',{name:target,exact:true}).click();await page.waitForTimeout(100);}await page.getByRole('button',{name:'Play guide',exact:true}).click();await page.getByRole('button',{name:'Pause Now playing'}).waitFor();results.offlineAudio=true;await settings(page);await page.getByRole('button',{name:'Remove saved passage',exact:true}).click();await page.getByRole('button',{name:'Confirm removal',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.offline-status')?.textContent.includes('Not saved on this device'));assert(await page.evaluate(()=>!!localStorage.getItem('fia.workspace.mark-1-1-13.v2')));results.removalPreservesProgress=true;await page.reload();await page.waitForFunction(()=>document.querySelector('[data-testid="current-unit"]')||document.querySelector('.loading-state [role="alert"]'));if(await page.getByTestId('current-unit').count()){await settings(page);await page.waitForFunction(()=>document.querySelector('.offline-status')?.textContent.includes('Not saved on this device'));}else{assert((await page.locator('body').innerText()).includes('app shell is open'));}results.shellWithoutPackTruthful=true;
await context.close();context=null;fs.writeFileSync(evidence+'/BROWSER.json',JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results));}finally{if(context)await context.close();await new Promise(r=>server.close(r));}
