import json,pathlib,subprocess,hashlib
P=pathlib.Path('/tmp/fia-derivative-preparation'); R=pathlib.Path('/tmp/fia-alignment-main-0c21899/public'); catalog=json.loads((P/'descriptors.json').read_text()); native=json.loads((P/'NATIVE-SAMPLES.json').read_text()) if (P/'NATIVE-SAMPLES.json').exists() else {}; audioPass=len(native.get('records',[]))>=2 and all(x.get('ended') for x in native.get('records',[])); spanishPass=any('/spa/' in x['sourcePath'] for x in native.get('records',[])); accepted=[]; receipts=[]; seen=set()
for d in catalog['entries']:
 d=dict(d);raw=R/d['sourcePath'].lstrip('/');probe=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_streams','-show_format','-of','json',str(raw)]));s=probe['streams'][0];b=raw.read_bytes();key=hashlib.sha256((d['sourceSha256']+d['recipe']).encode()).hexdigest();out=P/(key+'.bin');valid=hashlib.sha256(b).hexdigest()==d['sourceSha256'] and len(b)==d['sourceBytes'] and hashlib.sha256(out.read_bytes()).hexdigest()==d['sha256']
 if d['kind']=='audio':
  delta=d['durationSeconds']-float(probe['format']['duration']);d['sourceDurationSeconds']=float(probe['format']['duration']);valid=valid and abs(delta)<=.15;eligible=valid and audioPass and (spanishPass or '/spa/' not in d['sourcePath']);reason='native representative codec plus individual decode/hash/duration' if eligible else 'pending native language sample or duration gate'
 else:
  valid=valid and d['width']<=s['width'] and d['height']<=s['height'] and abs(d['height']-d['width']*s['height']/s['width'])<=1
  subprocess.run(['ffmpeg','-v','error','-i',str(out),'-f','null','-'],check=True,capture_output=True)
  eligible=valid;reason='root representative photo/map visual acceptance plus individual dimension/aspect/decode/hash'
 duplicate=(d['sourceSha256'],d['sha256']) in seen;seen.add((d['sourceSha256'],d['sha256']));d['eligible']=bool(eligible and not duplicate);d['acceptance']=reason if not duplicate else 'identical output duplicate';accepted.append(d);receipts.append({'sourcePath':d['sourcePath'],'sha256':d['sha256'],'valid':bool(valid),'eligible':d['eligible'],'reason':d['acceptance']})
result={'version':1,'sourceCommit':catalog['sourceCommit'],'sourceBase':'https://fia.klappy.dev','entries':accepted};(P/'qualified.json').write_text(json.dumps(result,indent=2)+'\n');(P/'QUALIFICATION.json').write_text(json.dumps({'audioRepresentativePass':audioPass,'spanishRepresentativePass':spanishPass,'records':receipts},indent=2)+'\n');print(json.dumps({'entries':len(accepted),'eligible':sum(d['eligible'] for d in accepted),'spanishNative':spanishPass}))
