import json,hashlib
from pathlib import Path
H=lambda s:hashlib.sha256(s.encode()).hexdigest()
inputs=json.load(open('audit/TRANSLATION-INPUTS.json'));review=json.load(open('translation-a/reviews/INDEPENDENT-176f963.json'))
texts=['''<blockquote><p>Esta es una manera en que podrían ayudar a explicar el arrepentimiento:</p><p>Dibujen o marquen un camino. Un extremo del camino termina en un lugar muy peligroso: una fogata, un precipicio o cualquier cosa que sea peligrosa. El otro extremo del camino termina en un lugar bueno: quizás una mesa con comida, un jardín bonito o cualquier objeto que ayude a las personas a ver que este es un buen lugar.</p><p>Luego hagan que algunas personas caminen por este camino hacia el lugar peligroso. Representen a estas personas haciendo cosas malas por el camino, como golpearse unas a otras o robar. Después hagan que otra persona se acerque a ellas y les diga que deben arrepentirse.</p><p>Representen que algunas de las personas que caminan por el camino se dan cuenta de las cosas malas que han hecho y notan el lugar peligroso hacia el que están caminando. ¡Representen que se sienten muy mal! Luego representen que estas personas dan media vuelta y comienzan a caminar hacia el extremo bueno del camino. Ahora pueden representar que hacen cosas buenas.</p><p>Quizás una de las personas de su dramatización pueda <em>no</em> arrepentirse y terminar en el fuego o caer por el borde del precipicio.</p></blockquote>''','''<p>Corrección de sentido mediante traducción con IA: Dios le dijo al profeta Ezequiel que se acostara de costado durante semanas seguidas sin moverse. «De costado» describe la postura del cuerpo; no significa acostarse al lado de otra persona.</p>''']
rows=[]
for f,text in zip(review['findings'],texts):
 x=next(x for x in inputs if x['englishId']==f['id']);source=f.get('sourceHtml',f.get('source'));start=x['englishHtml'].index(source);end=start+len(source)
 row={'id':'term-109-repentance-enactment' if '109' in f['id'] else 'term-104-posture-correction','targetId':x['spanishId'],'language':'spa','lang':'es','label':'AI translated from English','content':text,'format':'html','sha256':H(text),'source':{'sourceId':f['id'],'sourceHtml':source,'start':start,'end':end,'offsetUnit':'Unicode code points','sourceSpanSha256':H(source),'sourceBodySha256':H(x['englishHtml']),'source':x['englishSource']},'provenance':{'method':'AI translation of independently identified source gap; separate corrective appendage','reviewFinding':f,'originalSpanishBodySha256':H(x['existingSpanishOriginalHtml']),'reviewStatus':'pending affected independent review'},'rights':{**x['rights'],'priorNoticesRetained':True},'presentation':{'meta':'AI translated from English · complemento separado; original español conservado','notice':'Ejemplo opcional de dramatización del original inglés.' if '109' in f['id'] else 'Corrección de sentido del original español: «a su lado» debe entenderse como «de costado». El texto original se conserva.'},'audio':{'available':False}}
 if 'existingSpanish' in f:
  a=x['existingSpanishOriginalHtml'].index(f['existingSpanish']);row['provenance']['originalAffectedSpan']={'text':f['existingSpanish'],'start':a,'end':a+len(f['existingSpanish']),'sha256':H(f['existingSpanish'])}
 rows.append(row)
Path('translation-a/CORRECTIONS.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
c=json.load(open('translation-a/COVERAGE.json'));c['newGapSupplements']=[r['id'] for r in rows]
for row in c['rows']:
 if row['englishId'] in [f['id'] for f in review['findings']]:row.update(newMissingSpanEstablished=True,status='Independent RETURN repaired by separate appendage; affected review pending',newSupplementIds=[r['id'] for r in rows if r['source']['sourceId']==row['englishId']])
c['remainingGate']='Affected independent review of two corrective appendages; full32 review receipt retained'
Path('translation-a/COVERAGE.json').write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n')
print('2 corrections with exact English and original Spanish spans; original pack unchanged')
